### ISSUE TITLE
Generate Interface Authoring stubs for C++

### ISSUE THREAD

**Issue by devhawk** [microsoft/xlang#128]
When using the -component flag, cppwinrt will generate authoring stubs for all runtime classes in all of the -input metadata files (modulo any -include/-exclude filter flags). cppwinrt should also generate authoring stubs for all non-exclusive interfaces as well.

**Comment by kennykerr** [comment]
I'll revisit this if and when there is a taker, such as the VS IDE, that would use this feature.
