### ISSUE TITLE
ABI support for Object Equality

### ISSUE THREAD

**Issue by devhawk** [microsoft/xlang#133]
@bbowman [suggested](https://github.com/Microsoft/xlang/pull/119/files#r247203067) that the xlang ABI should have a mechanism for equality comparison. Many OO languages provide a mechanism for types to customize equality comparisons:

* dotnet [Object.Equals methon](https://docs.microsoft.com/en-us/dotnet/api/system.object.equals) 
* Python [\_\_eq\_\_ magic method](https://docs.python.org/3/reference/datamodel.html#object.__eq__)
* Java [Object.equals method](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#equals\(java.lang.Object\))
* Objective-C [NSObject isEqual](https://developer.apple.com/documentation/objectivec/1418956-nsobject/1418795-isequal)

Need to decide if this should be added as a method to IXlangObject, somehow shoe-horned into IXlangObject::GetInfo, or be a seperate interface accessed via QI

**Comment by devhawk** [comment]
Another option is to support seperate objects. dotnet has [IEqualityComparer<T>](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.iequalitycomparer-1) and [IComparer<T>](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.icomparer-1)

**Comment by EliasAE** [comment]
Hi, my first involvement in this project, so happy for any feedback.

I think that using separate object and interfaces for equality comparison is preferable, based on the below arguments.

There are two typical types of equality: reference equality (such as `Object.ReferenceEquals` method in .NET) and value equality (such as `IEquatable<T>` interface in .NET).

Reference equality is interlinked with the ABI and the associated definition of an object, as opposed to a "bag of interfaces". However, I think the value equality is not a property of the ABI, only of the type system. For example, value equality can be implemented without a notion of "objects" (such as string equality in C with `strcmp`). Furthermore, value equality is often multi-faceted and configurable, such as case-insensitive compared to case-sensitive string comparison in the `StringComparer` in .NET

In addition, not all ABI have a concept of value equality on objects, for example an xlang projection to WinRT would not be able to easily project value equality. 

Therefore, I propose that the xlang ABI excludes any implementation of value equality, and that value equality is only a part of the type system through specific interfaces, such as `IEquatable<T>` or similar.
Furthermore, I propose that the xlang ABI implements reference equality. As xlang objects are based on `IUnknown`, I propose xlang adopts the `IUnknown` definition and implementation of reference equality, defined in the Remarks section here: [IUnknown Reference](https://docs.microsoft.com/en-us/windows/desktop/api/unknwn/nf-unknwn-iunknown-queryinterface%28refiid_void%29)
"For any one object, a specific query for the IUnknown interface on any of the object's interfaces must always return the same pointer value."

That is, to test if two references (`a` and `b`) are referring to the same object, the following approach is used:
* Perform a `QueryInterface` on reference `a` asking for `IUnknown`
* Perform a `QueryInterface` on reference `b` asking for `IUnkonwn`
* Compare the pointer values obtained above for equality to determine if `a` and `b` points to the same object.

This also aligns with the assumptions already made in the XSPEC01, where there is an assumption of a “object identity”, very similar to `IUnknown` identity rules for aggregated objects:
“… These aggregated objects delegate identity and lifetime to the originally activated object in the composition chain (called the controlling object). …”

The reference equality can then be suitable exposed in languages projections as necessary.
