### ISSUE TITLE
Any plan for Node.JS?

### ISSUE THREAD

**Issue by be5invis** [microsoft/xlang#135]
Developing and distributing a native extension for Node.js is a disaster, as every Node dev know.

**Comment by devhawk** [comment]
Someone asked me about NodeJS on Twitter [just the other day](https://twitter.com/DevHawk/status/1085369891635392512)!

Yes, we absolutely want to support Node.js. Actually, we want to support JS generally - server-side and client side. WinRT supports JS, so we have a decent idea how a JS projection should look. The challenge with JS is the various implementations ([V8](https://v8.dev/), [Chakra](https://github.com/microsoft/ChakraCore), [SpiderMonkey](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey), [JavaScriptCore](https://developer.apple.com/documentation/javascriptcore)) and the various hosts ([Node.js](https://nodejs.org), [Cordova](https://cordova.apache.org), [React Native](https://facebook.github.io/react-native/), various web view components, etc). We can't afford to build seperate projections for each of those combinations. My current (completely unvetted) opinion is that Node's [N-API](https://nodejs.org/dist/latest-v10.x/docs/api/n-api.html) does a great job abstracting away JS engine implementation details. I'd love to see other JS hosts support that API.

**Comment by be5invis** [comment]
Since Node is the mostly-wide-used platform that supports native extension it would be a good start point.

**Comment by devhawk** [comment]
Luckily, the most widely-used JS host also has the plugin abstraction API I think we should target :smile:
