### ISSUE TITLE
Containers like IVector/IObservableVector should support reverse iterators

### ISSUE THREAD

**Issue by jevansaks** [microsoft/xlang#141]
I was recommending to a colleague that they use an STL algorithm instead of a manual for loop but in their case they were searching backwards so they couldn't use rbegin/rend with std::find_first_of. 

Please add rbegin/rend support to all the random access containers in C++/WinRT. Thanks!

**Comment by devhawk** [comment]
xlang / cppwinrt should totally add this. However, @jevansaks I think you could unblock your colleague with a custom implementation of winrt::impl::fast_iterator that decrements the index in operator++.

**Comment by jevansaks** [comment]
Thanks!!
