### ISSUE TITLE
xlang cmake builds are unreliable

### ISSUE THREAD

**Issue by kennykerr** [Microsoft/xlang#149]
C:\git\xlang\src\tool\python\code_writers.h(1989): warning C4189: 'category': local variable is initialized but not referenced

C:\git\LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/LTCG' specification

**Comment by kennykerr** [comment]
More trouble. When attempting to build a single project (e.g. cppwinrt) Visual Studio insists on building everything from the Python tool to the test projects.

![image](https://user-images.githubusercontent.com/9845234/52071025-f9262880-2536-11e9-9ae1-c62687e4c2b2.png)

**Comment by devhawk** [comment]
Really, an image of the build spew?

**Comment by devhawk** [comment]
I just checked the build locally and on the [build server](https://dev.azure.com/msft-xlang/public/_build/results?buildId=468) and did not see the python code_writers warning or the link warning.

**Comment by devhawk** [comment]
And I opened master branch in VS locally, chose the cppwinrt project as per the image above and chose Build -> Build (Project) cppwinrt from the menu. Only cppwinrt built, as expected. Closing as no repro.

In the  image above, it looks like the entire repo was built. I'm thinking @kennykerr selected CMake -> Build All by mistake.

**Comment by kennykerr** [comment]
Thanks for taking a look. There's still something subtle going on here, but I'll try to get a repro to show you when I'm back in the office.
