### ISSUE TITLE
src\test\cpp\metadata should have contract metadata not runtime metadata checked in

### ISSUE THREAD

**Issue by devhawk** [Microsoft/xlang#158]

**Comment by kennykerr** [comment]
Ideally the repo shouldn't contain any binaries. If only the SDK was available as a small package that contained only winmd files... via a package manager that is actually friendly to C++ projects. Something like https://conan.io/

https://youtu.be/DHOlsEd0eDE?t=2598

**Comment by devhawk** [comment]
Totally agree. Any idea which team @ MSFT we should talk to about that? 😝 

I experimented with using vcpkg to pick up the libffi dependency I needed for the [devhawk/foo branch](https://github.com/Microsoft/xlang/tree/devhawk/foo). Wasn't really happy with it. As far as I can tell, there is no binary distribution of vcpkg. That's not a show stopper for local development IMO, but it's a huge issue for build server. I ended up using the [export command](https://vcpkg.readthedocs.io/en/latest/users/integration/#export-command) for libffi, but that entailed building the library on my local machine and checking in the binaries. Isn't the point of using a package manager is to AVOID checking in binaries?

I need to look at Conan. I also discovered [PMM](https://github.com/vector-of-bool/pmm/) which is integrated with CMake and can pull from conan and vcpkg.

**Comment by devhawk** [comment]
There is also [CMake integration for Conan](https://github.com/conan-io/cmake-conan) we should investigate. Ideally, our code package manager should be integrated into CMake so we can pull packages down and build them as part of the build process

**Comment by kennykerr** [comment]
Right, in general though (at least for the C++ tools) there will be few if any dependencies. I'm actually more interested in looking at the package managers as a way to get xlang tools out there rather than pulling things in. We need official GitHub releases and then NuGet and Conan et al can pick up those official releases so that a wide variety of customers can use our binaries qiuckly and easily in their varied toolchains.

**Comment by devhawk** [comment]
From a publishing perspective, we should support as many package managers as possible I would think

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
