### ISSUE TITLE
cpp_test AsyncProgress and Events tests failing when run as part of Azure pipeline

### ISSUE THREAD

**Issue by devhawk** [microsoft/xlang#161]
Example: https://dev.azure.com/msft-xlang/public/_build/results?buildId=510&view=ms.vss-test-web.build-test-results-tab

I'm going to disable these tests. We will use this issue to track fixing and re-enabling them

**Comment by kennykerr** [comment]
👍

**Comment by devhawk** [comment]
FYI, I tagged the two tests [!hide][failing] so they are excluded from a default test run, but can be manually executed by calling cpp_test.exe [failing]
