### ISSUE TITLE
Provide mechanism to pass build pipeline version down to cmake

### ISSUE THREAD

**Issue by devhawk** [Microsoft/xlang#170]
Currently, src\tool\cpp\cppwinrt\version.h is updated by our internal build system. We should be generating this file as part of the cmake compile process, as demonstrated in the [CMake tutorial](https://cmake.org/cmake-tutorial/#s1)

**Comment by Scottj1s** [comment]
Rather than using version.h as the version source for other projects, the version number should be explicitly passed to cmake and propagated down.

**Comment by devhawk** [comment]
So we would pass XLANG_VERSION_STRING (or it's equivalent) into cl as a command line parameter for cpp/cppwinrt project?

**Comment by Scottj1s** [comment]
We still need to keep the cpp\cppwinrt\version.h around (it's included in the projection).  But other projects (natvis, nuget, vsix) could do their own versioning thing and not depend on cppwinrt.

**Comment by devhawk** [comment]
It sounds like we can seperate this into to parts.

1. Use a cmake variable to track cppwinrt version number. We'd generate version.h with that and use it for package projects that need the version information
2. Enable passing in the cppwinrt version number from the build pipeline (with a resonable default for local build)

**Comment by Scottj1s** [comment]
Fixed by #172
