### ISSUE TITLE
seperate version info for C++/WinRT from the rest of xlang

### ISSUE THREAD

**Issue by devhawk** [Microsoft/xlang#171]
C++/WinRT's version.h currently defines the macro XLANG_VERSION_STRING as "2.0.0". C++/WinRT may be up to v2.0.0, but there's no way we should be considering anything else in the xlang repo even at 1.0.0 level. We need seperate version macros for each tool.

**Comment by Scottj1s** [comment]
Is the request here simply to rename the macro, which is already specific to the cppwinrt project?

**Comment by devhawk** [comment]
Yes. At this point, only the C++ projection uses this macro. I'm thinking it should be CPPWINRT_VERSION_STRING

**Comment by kennykerr** [comment]
C++/WinRT no longer uses a version.h and now picks up the version from the build (whatever that might be). So I consider this done. Feel free to reopen if there's still an issue that I'm missing.
