### ISSUE TITLE
version.rc is not being included in cppwinrt project build

### ISSUE THREAD

**Issue by Scottj1s** [Microsoft/xlang#173]
It appears that version.rc is never being built or linked into cppwinrt.exe.  With the retirement of cppwinrt's version.h (PR 172), something like a CMAKE_RC_FLAGS will probably need to be created in cppwinrt/CMakeLists.txt to pass the version number to rc.exe.

**Comment by kennykerr** [comment]
Funny, I got this for free with vcxproj. 😉

**Comment by kennykerr** [comment]
Done.
