### ISSUE TITLE
C++/WinRT needs Windows builds to build with Clang as well as Visual C++

### ISSUE THREAD

**Issue by kennykerr** [microsoft/xlang#175]
We currently only build with Clang on non-Windows platforms. That means that C++/WinRT itself is never built with Clang as part of the build. We have a growing number of teams that need to use C++/WinRT with Clang on Windows so this is becoming very important.

**Comment by MarkIngramUK** [comment]
Is there much work required to get the Windows builds working with Clang? From my perspective I would be interested in support for both `clang` and `clang-cl`.

**Comment by kennykerr** [comment]
You can manually build with Clang. I describe [how to do it here](https://github.com/microsoft/xlang/blob/7e91d80930791a2c6414338d503e8d17e258c43f/src/tool/cppwinrt/cppwinrt.props#L22). VS is expected to support Clang natively in a future update. At that point, you'll be able to pick the compiler directly inside Visual Studio.

**Comment by MarkIngramUK** [comment]
Thanks Kenny. What about when building via CMake? Is that (or will that be) a supported scenario?

**Comment by kennykerr** [comment]
That should work as well, although we don't really use cmake for C++/WinRT development. You are of course free to use whatever build system you wish for your own projects. C++/WinRT is used inside Clang/CMake projects. Typically projects will a custom CMake command to run cppwinrt.exe to generate the headers, but I don't know much about that.

**Comment by kennykerr** [comment]
Moved to https://github.com/microsoft/cppwinrt/issues/368
