### ISSUE TITLE
ReactXP as cross-platform UI abstraction layer

### ISSUE THREAD

**Issue by kolohelios** [microsoft/xlang#179]
I heard Harry talk about Xlang yesterday (which is my first introduction to it) and simultaneous with great excitement I was left wondering if there could be synergies with [ReactXP](https://microsoft.github.io/reactxp/). It's being driven by the Skype team and already supports iOS, Android, and Windows 10 – as well as the web. With Electron wrappers, it can also support Mac OS X, Windows 7 and 8, and Linux. And the web could in theory also be supported through compiling Xlang to WebASM if that was of interest. ReactXP could be a good choice because it supports markup, styling, and UI interactions with JS/TS that are already familiar to UI developers.

**Comment by kennykerr** [comment]
Thanks for the heads up about ReactXP. We have no plans in that regard at the moment.
