### ISSUE TITLE
Project Python names with correct casing

### ISSUE THREAD

**Issue by zooba** [Microsoft/xlang#201]
For comfortable use from Python, it would be ideal for names to be converted into the typical casing used by idiomatic Python code.

Kind | Casing
---|---
Namespace | lowercase
Class/Interface | PascalCase
Enum | PascalCase
Function/method | lower_snake_case
Constant | UPPER_SNAKE_CASE
Enum value | UPPER_SNAKE_CASE
??? | ???

(Happy to add more, but I need reminding what else is there.)

The rule for converting PascalCase to snake_case is to find all sequences of one or more uppercase characters and insert an underscore before the last one. So `MyClass` becomes `My_Class` while `IODevice` becomes `IO_Device` (`IOD`->`IO_D`). Then upper/lower the whole thing.

Since this conversion may cause collisions, ideally there'd remain a way to access names by their unmodified form, probably through a helper function (`obj.my_function` or `get_by_original_name(obj, "MyFunction")`).

**Comment by devhawk** [comment]
Namespaces are already projected as lowercase (see https://github.com/devhawk/pywinrt-output/tree/master/generated/pyrt/windows for example).

WinRT doesn't have constants beyond enum values and WinRT uses PascalCasing generally for type and member names. So I think that means we are good on type names. Please confirm. 

I assume we use lower_snake_case for *all* type members except Enum values? in particular, what about struct field names? I'm assuming lower_snake_case there 

So that leaves 
- [ ] lower snake case non enum value type members (class/interface methods, properties and events, struct fields)
- [ ] upper snake case for enum value members

**Comment by zooba** [comment]
Looks good to me. Feel free to update my original table if you only want those ones called out

**Comment by zooba** [comment]
Parameter names should be lower snake case as well.

**Comment by devhawk** [comment]
My [first draft on write_snake_case](https://github.com/Microsoft/xlang/blob/devhawk/pyname/src/tool/python/code_writers.h#L15) adds an underscore if the current character is upper and the next character is lower. Spot checking the namespaces I use for test looks pretty good...except for places where we use UInt. Those look wrong. I'm thinking I should special case those. 

@zooba, @BrentRe I'm interested in your thoughts here

``` csharp
// C# projection
public enum PropertyType
{
    Empty = 0,
    Int16 = 2,
    UInt16 = 3
    OtherType = 20,
    UInt8Array = 1025,
    Int16Array = 1026,
    // remaining values omitted
}

public enum DirectXPixelFormat
{
    Unknown = 0,
    R32G32B32A32Typeless = 1,
    R32G32B32A32Float = 2,
    R32G32B32A32UInt = 3,
    R32G32B32A32Int = 4,
    // remaining values omitted
}
```
``` python
# Python projection
class PropertyType(enum.IntEnum):
    EMPTY = 0
    INT16 = 2
    U_INT16 = 3
    OTHER_TYPE = 20
    U_INT8_ARRAY = 1025
    INT16_ARRAY = 1026
    # remaining values omitted

class DirectXPixelFormat(enum.IntEnum):
    UNKNOWN = 0
    R32G32B32A32_TYPELESS = 1
    R32G32B32A32_FLOAT = 2
    R32G32B32A32U_INT = 3
    R32G32B32A32_INT = 4
    # remaining values omitted
```

**Comment by devhawk** [comment]
Special casing "UInt" looks much better

``` python
class PropertyType(enum.IntEnum):
    EMPTY = 0
    INT16 = 2
    UINT16 = 3
    OTHER_TYPE = 20
    UINT8_ARRAY = 1025
    INT16_ARRAY = 1026

class DirectXPixelFormat(enum.IntEnum):
    UNKNOWN = 0
    R32G32B32A32_TYPELESS = 1
    R32G32B32A32_FLOAT = 2
    R32G32B32A32_UINT = 3
    R32G32B32A32_INT = 4

**Comment by BrentRe** [comment]
Agreed

**Comment by zooba** [comment]
Actually, now you bring that up, we may have had an exception in the past for `UUl` as distinct from `UUUl`. But special casing UInt is also likely fine.
