### ISSUE TITLE
Decoding ECMA-335 generic types

### ISSUE THREAD

**Issue by raffaeler** [microsoft/xlang#216]
Hi, I am trying to follow the x-lang approach to write the interop for nodejs using N-API.
I am only doing experiments and started working on the xlang ecma library. I can currently dump signatures for properties and methods but had some difficulty in decoding generic types such as Task<T> and others.
Can someone point me to an example of decoding generic types?

Thank you!

**Comment by DefaultRyan** [comment]
Generic type definitions are pretty straightforward. xlang's `TypeDef` provides a `GenericParam()` method that will return a pair of iterators for a range of its declared `GenericParam` entries. This is where you get the generic param names - the `K` and `V` in ``IMap`2<K, V>``.

Next is referring to those generic params inside your definition. Still not too complicated. Sticking with our example, xlang will parse the method signature for ``bool IMap`2<K, V>.HasKey(K)`` and produce a `MethodDefSig` where the return type refers to `ElementType::Boolean` and holds a single parameter, a `GenericTypeIndex` holding an index of 0, which refers to the owning type's (`IMap`) first generic parameter `K`.

The trickier part is references and instantiations of generic types. In xlang, this is handled by `GenericTypeInstSig` - its `GenericType()` and `GenericArgs()` methods return what you'd expect, the generic type being instantiated and the type args supplied in that instantiation.

Sticking with the `IMap` example, the method signature for ``IMapView`2<K, V> IMap`2<K, V>.GetView()`` says the return type is a `GenericTypeInstSig` that refers to ``IMapView`2``, with two generic args: a couple `GenericTypeIndex` with index of 0 and 1.

Here's a bigger, more complex example. `StringMap` has the method `First()` that returns ``IIterator`1<IKeyValuePair`2<string, string>>``. In xlang, this method's return type gives you a `GenericTypeInstSig` that refers to ``IIterator`1``, with one generic arg - which is itself a `GenericTypeInstSig` that refers to ``IKeyValuePair`2`` with two generic args, both of which are `ElementType::String`.

Hope that helps.

**Comment by raffaeler** [comment]
Thank you @DefaultRyan 
**Generics on Types**: I could easily get the definitions. I did not expect iterators but your suggestion immediately brought the solution.

**GenericTypeIndex**: I stole the visitor in the tools, so I already got the GenericTypeIndex to retrieve the generic type from the owning type.

**GenericTypeInstSig**: Still no luck. In the visitor I have a "auto && type" and the intellisense does not help me in understanding what is that. I did not find a way to get the generic types from there.

**Generic Method**: There is a last case where `T Mul<T>(T tx, T ty)` is defined. When I call `method.Signature()` it **throws** with `"Unrecognized ELEMENT_TYPE encountered"` and ElementType is MVar (0x1E).

Could you help me for the last two cases?
Thanks!

**Comment by kennykerr** [comment]
I suspect you're using the metadata reader to read .NET metadata. We've only tested with WinRT metadata, which is a subset of .NET metadata (ELEMENT_TYPE_MVAR is not used by WinRT).

Regarding IntelliSense, have you tried the xlang.meta.natvis visualizer?

**Comment by raffaeler** [comment]
Hi @kennykerr, yes, I am trying to read .NET netstandard class library since I already worked on interfacing in-process .net core with nodejs.
If this is not possible, I will have to rely on .NET itself in order to build a C++ set of descriptors of the ECMA metadata for the assemblies ... weird but I don't see other solutions.

With regards to the Intellisense:
- currently there is no data at all (it does not even show the tooltip
- I dropped the cppwinrt.natvis and cppwinrtvisualizer.dll into the Visualizers folder, but could not see any real improvement. Did I miss something?

Thanks

**Comment by kennykerr** [comment]
I don't object to adding support for .NET metadata if it doesn't require major changes. We'd be happy to review a PR. 😉 

@Scottj1s may have some tips on how to get the visualizer working. We also have plans to publish some more content on that. It's just very new.

> If this is not possible, I will have to rely on .NET itself in order to build a C++ set of descriptors of the ECMA metadata for the assemblies ... weird but I don't see other solutions.

It might be helpful to understand what you are trying to achieve here. Keep in mind that the WinRT subset is that which is well defined across an ABI boundary. The rest is not necessarily stable. We can also chat in person at the MVP summit next week (if you're coming).

**Comment by raffaeler** [comment]
Sure I am available to add that support ... it mostly depends how much I can get familiar with the code.

I will be in Redmond starting from this Fri, so yes, let's continue the discussion face to face :)

**Comment by Scottj1s** [comment]
Unlike pure natvis scripts, which can just be copied into the visualizer folder, the cppwinrtvisualizer.dll (and natvis) must be installed via VSIX.  You can build that VSIX yourself from src\package\vsix, and install it.  This might be useful if you're using VS 2019, which we haven't release support for yet (expect a simultaneous RTM).

**Comment by raffaeler** [comment]
Thank you @Scottj1s 
I built all the solutions using cmake, but still can't see any vsix in the tree. Should I build it manually or what?

**Comment by kennykerr** [comment]
I think you only need this for metadata visualization:

https://github.com/Microsoft/xlang/blob/master/src/library/xlang.meta.natvis

**Comment by raffaeler** [comment]
Thank you @kennykerr. It works and I can finally start seeing something interesting

**Comment by raffaeler** [comment]
@kennykerr Supporting the `MVar` is not hard (is the same of `Var`) but I see no method to get the generic parameters specific of a method.
I don't remember if WinRT support generic methods whose generic parameter is specific of the method and not of the owning class.
Is this the case?

**Comment by DefaultRyan** [comment]
WinRT does not support generic methods.

Ryan

**Comment by DefaultRyan** [comment]
Like Kenny said, we'd be happy with getting support for generic methods to the metadata reader library. It just hasn't been a priority for us because generic methods don't exist in the WinRT type system.

Did the visualizer assist with cracking open the GenericTypeInstSig helper?

**Comment by devhawk** [comment]
FYI, there are a few updates to meta_reader in the [devhawk/RGM branch](https://github.com/Microsoft/xlang/tree/devhawk/RGM). That branch is likely orphaned but I can pull the meta_reader changes into a new branch and get them merged in

**Comment by raffaeler** [comment]
Thank you @devhawk while I see no changes in the `MVar` implementation, it would be great.
Please let me know as soon as you merge it :)

I hope to find the time to create a pull request before the upcoming MVP Summit, but definitely not sure.

**Comment by devhawk** [comment]
Just opened PR #223

**Comment by devhawk** [comment]
merged

**Comment by raffaeler** [comment]
Can someone give a hint on implementing the following on the `MethodDef` instead of `TypeDef`?
```
inline auto TypeDef::GenericParam() const
{
    return equal_range(get_database().GenericParam, coded_index<TypeOrMethodDef>());
}
```
I need searching the generic parameter names ...

**Comment by DefaultRyan** [comment]
The code should be exactly the same for `MethodDef`. All the traits helpers are already in place, so you should be able to literally copy this method and use the exact same function body.

**Comment by raffaeler** [comment]
Easier than I thought, it works, thanks :)

**Comment by raffaeler** [comment]
@DefaultRyan Ok, I got the entire decoding process work.
The problem is now with the visitor. Both the type and method generic types share the same `GenericTypeIndex` type in the visitor for the variant. The only difference is the `ELEMENT_TYPE` (0x13/Var for the generic type specified at class level, or 0x1e/MVar for the generic type specified at method level).

How do you prefer me to distinguish the two cases?

**Comment by devhawk** [comment]
I think you should add a GenericMethodIndex struct, similar to the GenericTypeIndex struct. GenericMethodIndex should be one of the TypeSig::value_type options so when TypeSig::ParseType enounters ElementType::MVar, it returns GenericMethodIndex { uncompress_unsigned(data) } similar to the way ParseType returns GenericTypeIndex{ uncompress_unsigned(data) } when it enounters ElementType::Var

**Comment by devhawk** [comment]
BTW, would love to see your work in progress @raffaeler if you want to open a draft PR or simply push to your own fork.

**Comment by DefaultRyan** [comment]
+1 on both of Harry's points.

**Comment by raffaeler** [comment]
Looks like everything is now working. Here is the pull request: https://github.com/Microsoft/xlang/pull/224
FYI I tested both pure generic methods and mixed (with a generic type from the owning class and another owned by the method itself).
HTH

**Comment by OneWingedShark** [comment]
I'm not sure if I should point it out here, as it's more general than ECMA-335, but it seems to me that limiting genericity to types is a fundamental design-flaw, especially as other languages like ML have some very robust properties.

As an example, consider Ada's ability to use values, types, subprograms, and other generics as formal generic parameters — it allows the so-called "dependency injection" in a straightforward manner, like so:
```
   Generic
      Type Element is private;
      Type Index   is (<>);
      Type Element_Vector is Array(Index Range <>) of Element;
      with Function  "<"( Left, Right : Element ) return Boolean is <>;
   Procedure Generic_Sort( Object : in out Element_Vector );
```
wherein the `<` operator is the dependency being injected and the ordering of the sort may be reversed by supplying `>` as the parameter instead of `>`.

The ability to use values is nice in that you can encode limits; example, given
```
   Generic
      Type Element is private;
      Maximum : Positive;
   Package Generic_Stack is
      Type Stack is limited private;
  --...
```
we can say `Package Integer_Stack is new Generic_Stack(Integer, 256);` to declare a package with a stack-type operating on `Integer` with the maximum size of 256.
