### ISSUE TITLE
Azure Pipelines builds aren't public

### ISSUE THREAD

**Issue by akoeplinger** [Microsoft/xlang#23]
The badge in the readme links to https://microsoft.visualstudio.com/Dart/_build/latest?definitionId=31784 which is only accessible inside of MSFT.

**Comment by udnaan** [comment]
Ditto. In order for the badge to inspire confidence, others should be able to inspect the build.

**Comment by devhawk** [comment]
Working on Azure pipeline VM definitions for  xlang. For now, they are in my fork of https://github.com/Microsoft/azure-pipelines-image-generation but we will add them to the xlang repo after we get them up and running. 

Anyone interested in taking an early look, here are the [Packer files](https://www.packer.io/)

* [Linux xlang build](https://github.com/devhawk/azure-pipelines-image-generation/blob/xlang/images/linux/xlang-build.json)
* [Windows xlang build](https://github.com/devhawk/azure-pipelines-image-generation/blob/xlang/images/win/xlang-build.json)

**Comment by devhawk** [comment]
Linux CI builds are enabled and public: https://dev.azure.com/msft-xlang/public/_build/latest?definitionId=1

Public Windows CI builds coming soon, so leaving this issue open

**Comment by devhawk** [comment]
I will close this when #92 gets merged
