### ISSUE TITLE
meta reader helpers around Extends() assume TypeRef

### ISSUE THREAD

**Issue by DefaultRyan** [Microsoft/xlang#249]
But in third party metadata, Extends can be specified via a direct TypeDef. Handle the TypeDef cases properly. Right now this applies to xlang::meta::reader::extends_type and get_base_class

**Comment by oldnewthing** [comment]
Also `get_category`.

**Comment by oldnewthing** [comment]
@DefaultRyan This issue has been resolved and can be closed.
