### ISSUE TITLE
Unclear how to enable desktop extensions in new headers

### ISSUE THREAD

**Issue by eklipse2k8** [Microsoft/xlang#269]
It looks like upgrading to latest nuget package now generates v2 of cppwinrt headers in the generated directory. However, it doesn't seem to be a way to reference the desktop extension and so many classes are missing.

```xml
  <ItemGroup>
    <SDKReference Include="WindowsDesktop, Version=10.0.18362.0" />
  </ItemGroup>
```

**Comment by Scottj1s** [comment]
fixed
