### ISSUE TITLE
Xlang - Will this bring XAML standard, and Windows UI Library to Linux, Android, iOS, Mac, etc

### ISSUE THREAD

**Issue by mdtauk** [Microsoft/xlang#28]
Looking through the design docs, I get the impression that the scope of this project abstracts the basic base types and other building blocks of building code for an app.  Assuming this API would be built on WinRT/UWP - would you imagine Xlang would allow for porting of much of the UWP API surface for use on other platforms - by projection of the compiled binaries, towards native ports of WinRT, or some translation to native framework equivalents?

Would XAML Standard be supported for rendering UI to native platform surfaces, as XAML is rendered to Direct X on Windows 10?

If it is just for Windows, why would there be a need to add yet another abstraction with language projections?

**Comment by devhawk** [comment]
We've added more description to the [project readme](https://github.com/Microsoft/xlang#overview) to answer this question. 

Please feel free to ask additional questions on this thread - we want to make sure we are effectively communicating the goals and non-goals of the xlang project.
