### ISSUE TITLE
Activation Factory has a potential to be ineffective

### ISSUE THREAD

**Issue by kingofthebongo2008** [Microsoft/xlang#292]
When one uses cppwinrt and has more types in it activation factory can slow down the instantiation of classes.
The reason is that there are a lot of string comparison, which can be linear.
A simple scheme with a compile time CRC technique might help here, so we compare only ints in a sorted array.
If you get a 40-50 types in a module can be a really a problem, if types are allocated with high frequency.

void* WINRT_CALL winrt_get_activation_factory(std::wstring_view const& name)
{
    auto requal = [](std::wstring_view const& left, std::wstring_view const& right) noexcept
    {
        return std::equal(left.rbegin(), left.rend(), right.rbegin(), right.rend());
    };

    if (requal(name, L"UniqueCreator.Graphics.BlendDescription"))
    {
        return winrt::detach_abi(winrt::make<winrt::UniqueCreator::Graphics::factory_implementation::BlendDescription>());
    }

    if (requal(name, L"UniqueCreator.Graphics.CompositionSwapChainResources"))
    {
        return winrt::detach_abi(winrt::make<winrt::UniqueCreator::Graphics::factory_implementation::CompositionSwapChainResources>());
    }

    if (requal(name, L"UniqueCreator.Graphics.ComputePipelineState"))
    {
        return winrt::detach_abi(winrt::make<winrt::UniqueCreator::Graphics::factory_implementation::ComputePipelineState>());
    }

    return nullptr;
}

**Comment by kennykerr** [comment]
Do you have an actual scenario where this is a problem? In practice I have not found this to be an issue for a few reasons:

* A call through `RoGetActivationFactory` is very expensive and the string comparisons are not the dominating factor. Anything else tends to be in the noise.
* The C++/WinRT factory cache avoids repeated calls to `RoGetActivationFactory`. 
* The `requal` function is specially designed to improve search time by first performing a size comparison and then comparing in reverse, avoiding repeatedly comparing the namespace.

**Comment by kingofthebongo2008** [comment]
I do not have such a scenario, because i am relatively new to winrt, i have
still 15 classes,
but i have thought that this may be an issue.
If the call is cached then i guess it is fine, just on the start of the
apps will be the slow down if any.
