### ISSUE TITLE
Xaml Compiler completion date

### ISSUE THREAD

**Issue by MRahilly** [Microsoft/xlang#293]

**Comment by kennykerr** [comment]
Can you share anything about the specific concern or issue you ran into? I can then loop in the Xaml compiler team as needed.

**Comment by MRahilly** [comment]
I have attached the solution files for which the following Xaml Compiler error appears:
[WhatSizeWithBindingConverter.zip](https://github.com/Microsoft/xlang/files/3055413/WhatSizeWithBindingConverter.zip)

1>Processing input metadata file C:\Users\MRahilly\source\repos\WhatSizeWithBindingConverter\x64\Debug\WhatSizeWithBindingConverter\Unmerged\App.winmd.
1>Processing input metadata file C:\Users\MRahilly\source\repos\WhatSizeWithBindingConverter\x64\Debug\WhatSizeWithBindingConverter\Unmerged\MainPage.winmd.
1>Processing input metadata file C:\Users\MRahilly\source\repos\WhatSizeWithBindingConverter\x64\Debug\WhatSizeWithBindingConverter\Unmerged\XamlMetaDataProvider.winmd.
1>Saved output metadata file WhatSizeWithBindingConverter.winmd.
1>Validating metadata file C:\Users\MRahilly\source\repos\WhatSizeWithBindingConverter\x64\Debug\WhatSizeWithBindingConverter\Merged\WhatSizeWithBindingConverter.winmd.
1>pch.cpp
1>FormattedStringConverter.cpp
1>App.cpp
1>MainPage.cpp
1>module.g.cpp
1>XamlMetaDataProvider.cpp
1>XamlTypeInfo.Impl.g.cpp
1>C:\Users\MRahilly\source\repos\WhatSizeWithBindingConverter\MainPage.xaml(13,10): XamlCompiler error WMC0001: Unknown type 'FormattedStringConverter' in XML namespace 'using:WhatSizeWithBindingConverter'
1>Done building project "WhatSizeWithBindingConverter.vcxproj" -- FAILED.

**Comment by kennykerr** [comment]
Adding @danzil

**Comment by danzil** [comment]
Because you're using the type in markup, you need to have it declared in IDL. The Xaml Compiler wants to validate all types it sees, and FormattedStringConverter only exists in the C++ land, not in metadata.
