### ISSUE TITLE
problem with cppwinrt.exe -lib option

### ISSUE THREAD

**Issue by ChrisGuzak** [Microsoft/xlang#310]
From: Jiin Park
I think this line is it 
   { "library", 0, 1, "Specify library prefix (defaults to winrt)" },
 
https://github.com/Microsoft/xlang/blame/master/src/tool/cppwinrt/cppwinrt/main.cpp
And the line has bug which is preventing printing the line.

**Comment by kennykerr** [comment]
Thanks! This has been fixed. #308
