### ISSUE TITLE
C++/WinRT 2.0.190408.1 can't compile IValueConverter

### ISSUE THREAD

**Issue by AndriiPrystaiSymphony** [Microsoft/xlang#311]
Compiler produces following error when trying to build StringFormatter converter from [Data binding quickstart sample](https://docs.microsoft.com/en-us/windows/uwp/data-binding/data-binding-quickstart) after migration to C++/WinRT 2.0:

> EXEC : error : Type 'Quickstart.StringFormatter' does not have a default interface

Environment details:

> Windows 10 Pro version: 10.0.17763.437
> Microsoft Visual Studio Community 2019 version: 16.0.1
> Windows 10 SDK version: 10.0.17763.0
> C++/WinRT extension version: 2.0.190408.1
> Microsoft.Windows.CppWinRT NuGet Package version: 2.0.190408.1

Project attached: [quickstart_formatting_or_converting_data_values_for_display.zip](https://github.com/Microsoft/xlang/files/3072951/quickstart_formatting_or_converting_data_values_for_display.zip)

I would be very grateful for any feedback you could be able to give me on this problem.

**Comment by kennykerr** [comment]
That error indicates that the developer failed to set the default interface for the given runtime class in IDL. Typically this is done with the [default] attribute. Adding @stevewhims to check whether this is a doc bug.

**Comment by AndriiPrystaiSymphony** [comment]
[default] attribute didn't help. This problem affects any runtime class definition that derives from an interface (e.g. Windows.UI.Xaml.Data.INotifyPropertyChanged or Windows.Foundation.IStringable, etc.)

Adding members/methods to .idl forces C++/WinRT 2.0 to generate Converter.

Made a quick test: Downgraded Microsoft.Windows.CppWinRT NuGet package to version="1.0.190211.5" and the following .idl compiles with no errors:

```
// Test.idl

namespace Quickstart
{
   // Fails under C++/WinRT 2.0. EXEC : error : Type 'Quickstart.CustomConverter1' does not have a default interface
   runtimeclass CustomConverter1 : Windows.UI.Xaml.Data.IValueConverter
   {
       CustomConverter1();
   }

   runtimeclass CustomConverter2 : Windows.UI.Xaml.Data.IValueConverter
   {
       CustomConverter2();
       void Stub(); // Workaround. Stub method forces C++/WinRT 2.0 to generate CustomConverter2
   }
}

**Comment by kennykerr** [comment]
What do you mean by "[default] attribute didn't help"? You need to ensure that the runtime class has a default interface. There are a variety of ways of ensuring that. One would be this (using a [default] attribute) to indicate that IValueConverter is the default interface:

```
   runtimeclass CustomConverter1 : [default] Windows.UI.Xaml.Data.IValueConverter
   {
       CustomConverter1();
   }
```

Are you saying this does not work? Another option would be by adding a method to the runtime class, which causes MIDLRT to synthesize a default interface (your second example). MIDL 2.0 also had more options, but here you have at least two to work with.

**Comment by AndriiPrystaiSymphony** [comment]
Not sure why, but build was genereting errors when [default] attribute was in .idl.
After you ensured me the solution with [default] attribute must work, I've brought it back and completely cleaned solution (Removed Generated Files, x64 and hidden .vs folder), rebuilt and.... success!
Thank you so much @kennykerr!

@stevewhims It would be great to replace StringFormatter.idl listing in [Formatting or converting data values for display](https://docs.microsoft.com/en-us/windows/uwp/data-binding/data-binding-quickstart#formatting-or-converting-data-values-for-display) with
```
// StringFormatter.idl
namespace Quickstart
{
    runtimeclass StringFormatter : [default] Windows.UI.Xaml.Data.IValueConverter
    {
        StringFormatter();
    }
}

// MainPage.h
#include "StringFormatter.h"
```

Just in case, fixed Quickstart project attached: [quickstart_formatting_or_converting_data_values_for_display_fixed.zip](https://github.com/Microsoft/xlang/files/3080289/quickstart_formatting_or_converting_data_values_for_display_fixed.zip)

**Comment by BrentRe** [comment]
The preferred, and best IMO, way to ensure a default interface in this scenario is to add the [default_interface] attribute to the runtime class. E.g.

    [default_interface]
    runtimeclass StringFormatter : Windows.UI.Xaml.Data.IValueConverter
    {
        StringFormatter();
    }

This forces MIDL to generate a IStringFormatter interface (which is empty as the class has no instance members), and make IStringFormatter the default interface. Then, should you subsequently add instance members to the class, they also end up in the default interface.

So you're not locked into IValueConverter being the default interface after subsequently adding instance members, which would then require a QI to get to the instance members.

**Comment by stevewhims** [comment]
I’ll use this technique, then, in the docs, and I’ll mention the reasoning. Thanks, Brent!
