### ISSUE TITLE
Proposal: Enable customization of namespace and type name suffixes for the generated implementation types.

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/xlang#316]
In C++/WinRT 1.0 and 2.0, implementation types are generated with the same name as the projected types in the ``implementation`` and ``factory_implementation`` namespaces. 

Example:

```
// MyClass.idl
namespace MyNamespace
{
    [default_interface]
    runtimeclass MyClass
    {
        MyClass();
    }
}

// MyClass.h
#pragma once

#include "MyClass.g.h"

namespace winrt::MyNamespace::implementation
{
    struct MyClass : MyClassT<MyClass>
    {
        MyClass() = default;
    };
}

namespace winrt::MyNamespace::factory_implementation
{
    struct MyClass : MyClassT<MyClass, implementation::MyClass>
    {
    };
}
```

## Problem statement
The fact that there are two types with the same name, is confusing to many engineers and requires careful examination of the included headers to determine if an implementation or a projected type would be instantiated. 

A possible solution is to fully qualify the type. This is the approach that the code generated by cppwinrt.exe takes, but has various problems:
- The generated implementation stubs only fully qualify types implemented within the same component.
- It is only required for types implemented within the same component, requiring engineers to know if a type they use is implemented in the same component or not.
- It is counter-productive to write fully qualified type names as namespaces can be quite long.
- Stack allocations cannot be detected within a coroutine, see limitation of heuristic below.

## Evidence of the problem
There is evidence that this is in fact a problem for component authors. 

In C++/WinRT 2.0 a heuristic was added for debug builds to assert when an implementation type is created on the stack, see [https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/news#help-with-diagnosing-stack-allocations](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/news#help-with-diagnosing-stack-allocations). However, as mentioned in the linked document, this doesn't work for coroutines.

Various bugs on my team were caused by engineers making this mistake or accidentally forgetting to fully qualify the type.

The [Windows UI Library](https://github.com/Microsoft/microsoft-ui-xaml) team doesn't seem to be using the implementation namespace for their implementation types, though it is unclear if that is because of this problem.

## Proposal
The proposal is to allow customization of the namespace and type names for the implementation types using two new command line parameters for cppwinrt.exe:

- ``-component_namespace_suffix``: Namespace suffix used for the namespace for the implementation types. This would default to ``implementation`` as that's what the V1 and V2 behavior is.

- ``-component_type_suffix``: Type suffix used for the name of the implementation types. This would default to empty string as in C++/WinRT V1 and V2 implementation types have the same name as the projected types.

This would allow for differentiating the implementation types by type name instaed of by namespace name. A project type ``MyClass`` could have an implementation type ``MyClassImpl`` (I picked Impl as it resembles the [pImpl idiom](https://herbsutter.com/gotw/_100/)). 

### Examples

Current C++/WinRT V1/V2 behavior would be achieved using the defaults or by specifying ``-component_namespace_suffix "implementation"``.

Using ``-component_namespace_suffix ""`` and ``-component_type_suffix "Impl"``, would generate the following:

```
// MyClass.h
#pragma once

#include "MyClass.g.h"

namespace winrt::MyNamespace
{
    struct MyClassImpl : MyClassImplT<MyClassImpl>
    {
        MyClassImpl() = default;
    };
}

namespace winrt::MyNamespace::factory
{
    struct MyClassImpl : MyClassImplT<MyClassImpl, implementation::MyClassImpl>
    {
    };
}
```

**Comment by jlaanstra** [comment]
I can contribute this, but would like to get feedback from other C++/WinRT users and the C++/WinRT team first.

**Comment by kennykerr** [comment]
Thanks for sending out the proposal before a PR! It's agreat way of collecting feedback before you invest a lot of time on an implementation. It sounds good to me. I'd also be interested in whether this would help @jevansaks adopt the generated module.g.cpp implementation. My only initial feedback would be to use lower_case option names as in `-component_type_suffix Impl`.

**Comment by jlaanstra** [comment]
Updated with lower_case option names. I'm still thinking through options to see if this is the right set of knobs to expose.

**Comment by jevansaks** [comment]
Does XamlCompiler currently assume anything for the C++/WinRT generated code about the type names? I assume it does. @danzil ?

> I'd also be interested in whether this would help @jevansaks Jevan Saks FTE adopt the generated module.g.cpp implementation.

It would help but I don't think it solves it because module.g.cpp assumes two things about my implementation:
1) The naming convention of the implementation header files
2) The namespace and naming convention of implementation types.

This proposal would help # 2 but not # 1 (yet). Also our convention is that implementation types live in the global namespace so I don't think a simple "suffix" fully solves # 2 for us.

@jlaanstra would there also be a `-component_factory_namespace` parameter? Or do we assume that factory types live in `::factory` under the -component_namespace_suffix?

**Comment by kennykerr** [comment]
Thanks @jevansaks, C++/WinRT 2.0 solves # 1 so this would get us closer. We'd potentially need this proposal to also support your global namespace approach.

**Comment by jlaanstra** [comment]
@jevansaks Current proposal doesn't include anything for the factory namespace. Do you think it's important to have that?

**Comment by jevansaks** [comment]
What I see in module.g.cpp today (I'm using cppwinrt.exe out of the SDK still) is that it assumes my factory types are in `winrt::Foo::Bar::factory_implementation::Baz`. So I only care about the factory namespace if module.g.cpp continues to care about it in this proposal.

**Comment by kennykerr** [comment]
When you use `/opt` in C++/WinRT 2.0 the `module.g.cpp` doesn't even care about that. It only looks the linker to resolve a function named `void* winrt_make_Namespace_Name()`. This avoids both the compiler rebuild and the dependence on any particular namespace/name for the actual implementation type. This function must simply return a pointer to the factory and you can define that wherever you like. For example:

```
void* winrt_make_Namespace_Name()
{
    return winrt::detach_abi(winrt::make<MyCustomNamedFactory>());
}
```

**Comment by jlaanstra** [comment]
The only thought I still have is: Should we actually allow customization of the suffix names or should we force ``implementation`` if you use the namespace suffix and ``Impl`` if you use the type suffix?

**Comment by kennykerr** [comment]
If Jevan is happy generating his DLL exports and ignore the generated module.g.cpp that's also OK. 

Yes, I'd still need to see a compelling case for more flexibility as it adds complexity and a support cost. I actually like the more uniform binary model. Default is what we have today "implementation" namespace and the alternative is "-Impl" name.

**Comment by danzil** [comment]
The only name that the Xaml Compiler assumes for C++\WinRT is the namespace "implementation" and the reason for that is because we didn't have uniform type construction at that time (i.e. local types still needed winrt::make while projection types would activate using their constructor).

**Comment by kennykerr** [comment]
Good point. Thanks Daniel. Now that C++/WinRT provides uniform construction, this becomes far less confusing. I am also addressing the limitations in the ability for C++/WinRT to detect and diagnose stack allocation errors at compile time and 100% of the time. Perhaps there is then less reason to support this degree of customization and avoid the added the complexity.

**Comment by jlaanstra** [comment]
@danzil @kennykerr I assume the xaml compiler will switch to use uniform construction when running with C++/WinRT 2? I still feel there is value in having easy distinguishable type names for implementation types.

**Comment by kennykerr** [comment]
Yes, @danzil and I are starting to talk about the design for the next major update to the Xaml compiler. 

> I still feel there is value in having easy distinguishable type names for implementation types.

The question is whether there is enough value to warrant the added complexity. I don't think there is and if you really want to go that route you can still do what Jevan has done and name it whatever you like.

**Comment by jlaanstra** [comment]
> The question is whether there is enough value to warrant the added complexity. I don't think there is and if you really want to go that route you can still do what Jevan has done and name it whatever you like.

I'll definitely give that a try and see how much extra code I have to write to make that work.
