### ISSUE TITLE
IValueConverter unresolved external symbol

### ISSUE THREAD

**Issue by MRahilly** [microsoft/xlang#319]
If there is an unresolved symbol LNK2019 error, this usually means that an implementation header is missing. It could mean that a winrt::make function template needs to be written and if so how as the documentation seems to refer only to calling the winrt::make function template?

module.g.obj LNK2019 unresolved external symbol void * __cdecl winrt_make_WhatSizeWithBindingConverter_FormattingStringConverter(void)

[WhatSizeWithBindingConverter.zip](https://github.com/Microsoft/xlang/files/3081330/WhatSizeWithBindingConverter.zip)

**Comment by kennykerr** [comment]
I believe @Scottj1s  just fixed this bug in the VS integration. In the short term, you can work around it by including the corresponding "Type.g.cpp" generated file at the top of your "Type.cpp" file.

**Comment by MRahilly** [comment]
I can't locate the Type.g.cpp or Type.cpp files. The build could be terminating before these get generated.

**Comment by Scottj1s** [comment]
You should find your WhatSizeWithBindingConverter.g.cpp and so on under "$(IntDir)Generated Files".  I did just add .g.cpp includes to the project and item templates, which I'll publish soon.

**Comment by MRahilly** [comment]
I don't seem to have a WhatSizeWithBindingConverter.g.cpp. I tried the FormattedStringConverter.g.cpp which appears to have relevant content but get a compiler error suggesting a missing pch.h.

**Comment by Scottj1s** [comment]
The projection assumes you're using a pch.  It will honor whatever name you use in your project - pch.h, stdafx.h, etc - but it isn't optional.

**Comment by MRahilly** [comment]
I will try to include FormattedStringConverter.g.cpp in the pch.h that I already have.

**Comment by MRahilly** [comment]
Attempting to include FormattedStringConverter.g.cpp in the pch.h seems to generate yet more issues.

**Comment by Scottj1s** [comment]
The .g.cpp file should be included in the corresponding runtime class implementation cpp, not in another header (like pch)

**Comment by MRahilly** [comment]
Including FormattedStringConverter.g.cpp inside FormattedStringConverter.cpp leads to C2039 'factory_implementation' is not a member of 'winrt::WhatSizeWithBindingConverter'

**Comment by Scottj1s** [comment]
Typically you would also include your implementation header, which in turn would include winrt/base.h, which will supply the needed definitions.

**Comment by MRahilly** [comment]
Scott, I will mull and brood over that. I usually associate omission of implementation headers with unresolved symbol linker errors - as opposed to C2039 above.

**Comment by Scottj1s** [comment]
Ok.  Your generated implementation header, under Generated Files/source, should have defined that namespace.  And you should then have copied that into your project.  Are you including the .g.cpp after that header?

**Comment by MRahilly** [comment]
Scott, Thanks for your time. Kenny refers above to a bug fix in VS integration. Is there an ETA on that?

**Comment by Scottj1s** [comment]
You're welcome!  The bug Kenny refers to is when using the VSIX item templates.  That was fixed and published yesterday, but may not apply to your situation.

**Comment by MRahilly** [comment]
I dream of Petzold PW6 samples being ported to C++/WinRT. That is going to need better programmer than I am.

**Comment by MRahilly** [comment]
When in Rome, do what the Romans do. When using the VSIX a complete understanding of the VSIX patterns is needed.

**Comment by MRahilly** [comment]
Some surgery on module.g.cpp got this resolved.
Thank you both
