### ISSUE TITLE
Enormous disk requirement for cppwinrt 2.0

### ISSUE THREAD

**Issue by mediabuff** [Microsoft/xlang#336]
I have a solution in with 10 or so cppwinrt projects. As the new version generates projections for each project (even for frame work libraries), the compile time is long and the disk storage some thing like 10G!. 

We definitely need an optimized way of doing this, at least for frame work projections and shared projects.

**Comment by mediabuff** [comment]
This platform has become totally unusable for any production quality work - humungous header files, long compile times, inordinate disk requirements, unstable and undocumented header naming conventions, unstable integration with not-so-robust xaml compiler, meta data merge/duplicate issues, random exceptions at runtime.

I am begining to like c++/cx  and all the glory of ^

**Comment by kennykerr** [comment]
Thanks for the feedback. A few observations:

* The headers have not gotten larger in C++/WinRT 2.0. 
* I suspect the bulk of the disk usage you're seeing is from PCH files. This too has not gotten larger in C++/WinRT 2.0. I am also steadily working to reduce the size wherever possible. 
* There are longer terms plans to avoid using PCH files altogether by switching to C++ modules and even C++ metaclasses in future.
* There are known issues with the Xaml compiler, MIDLRT, and MDMERGE tools. We have limited control over those tools but have plans to improve or replace them in future as needed. 
* If your use of C++/WinRT is predominantly for Xaml then you are likely running into the most issues as that scenario still needs a lot of work. All I can say is that I am personally investing very heavily in improving the experience of using Xaml from C++.
* With 10+ projects you can certainly save a lot of storage and build time by sharing PCH files across projects. Here's a how-to article:

https://devblogs.microsoft.com/cppblog/shared-pch-usage-sample-in-visual-studio/

**Comment by mediabuff** [comment]
Kenny
Thanks for the quick reply. I know you are very committed to this platform :-) I hope you are not the lone soldier within Microsoft making this production quality. At this point, sadly, for any serious xaml work - it has become impossible. I am in the process of rewriting my cppwinrt back to c++/cx.

Specific comments
1) I did'nt mean 2.0 gottern longer header files. cppwinrt being all of headers, with 2.0 not optimizing platform projections - creates all the issues of bloat and performance.

2) >>There are longer terms plans to avoid using PCH files altogether by switching to C++ modules

Waiting for almost 2 years, MS is not making progress. I see the Visual c++ team has gone into dormancy - not working on priority items, but keep fixing and user interface issues. Not seen any progress on the compiler space for last 6 months. For a trillion dollar company, this reengineering is taking umpteen years.

3) yes - serious issuues on XamlC, Midrt, mdmerge and overall poor productivity - compared to c# development.

Still not losing hope. Please press on other MS teams hard - just does'nt understand how MS is ignoring c++ development for Windows 8/10 for so many years !!

**Comment by kingofthebongo2008** [comment]
For speeding up the builds you can look at incredibuild
or fastbuild which is very nice.
They can share compiled cached files across the project.
You may try to split up the code base, looks to me that there is a big .sln
file that hosts everything.
And finally you may want to try nuget packages to use prebuilt code,
because very often one works in a small subset of the files.
I suggest investing some time in these tools, since the code base is
getting larger and larger over the years, it is a sign for a healthy project

**Comment by mediabuff** [comment]
Stefan - thanks for the suggestions.
>>For speeding up the builds you can look at incredibuild
or fastbuild which is very nice.
Not ready to add another third-party tool - in an already complex setting of UWP development - troubleshooting becomes much harder.

>>You may try to split up the code base, looks to me that there is a big .sln
file that hosts everything.
Which is exactly VS projects are for. Modules/DLL/Libs

>>And finally you may want to try nuget packages to use prebuilt code,
Not feasible when you are iterating and developing - still unstable api across modules.

>>I suggest investing some time in these tools, since the code base
A better approach would be for MS to get c++ developement closer to modern day productivity - at least bit robust as c++/cx - if not the gold standard .net/csharp development

**Comment by kennykerr** [comment]
This is great feedback but not really actionable by our team. Your best bet is to make it known to the C++ team directly:

https://developercommunity.visualstudio.com/spaces/62/index.html
