### ISSUE TITLE
There are cases when cppwinrt will generate code with empty file names.

### ISSUE THREAD

**Issue by kingofthebongo2008** [Microsoft/xlang#347]
Hello 
1. After changing an interface to a runtime class, the generated file has no name. I have tried to delete .vs all .winmd files, no success.
2. Can we have empty classes ? I want to be able to tag certain functions to accept only certain classes.

[Generated Files.zip](https://github.com/Microsoft/xlang/files/3110606/Generated.Files.zip)
[idl.zip](https://github.com/Microsoft/xlang/files/3110610/idl.zip)

**Comment by kennykerr** [comment]
Can you share a minimal repro? The simplest is a winmd file that demonstrates the problem along with the cppwinrt.exe command line arguments that causes the behavior in question.

**Comment by kingofthebongo2008** [comment]
Well,
I have fixed the problem.
I had a runtimeclass BackBuffer and a property BackBuffer
This caused the issue.
You can see this in the idl files supplied
