### ISSUE TITLE
Needs to build on MacOS

### ISSUE THREAD

**Issue by migueldeicaza** [microsoft/xlang#35]
This does not seem to be designed to work on Unix.

**Comment by mdtauk** [comment]
I think I need the "For Dummies" version to understand what the purpose of this project is.  It talks about acting as a bridge between similar concepts from one language to another, but beyond that what is the goal?  

It is alongside the UWP language projections as I understand it, but is the intention to bring in Languages like Java, Go, Dart, Objective-C, Swift - for compiling apps for Windows?

It has been decided it should not be about taking Windows apps in C#, C++, VB, F# into other platforms. As there is no plan to port APIs.

So if the goal is to bring in new developers working in different languages to the native Windows ones - does that make Windows a receptacle for apps - but leaves the likes of C#, F#, etc without a confident cross platform future?  There is Xamarin of course, but will there be any effort to persuade Google and Apple to add better support in their platforms for Windows originated apps to cross over?

**Comment by devhawk** [comment]
#46 will get the platform adaptation layer + tools compiling on Ubuntu 18.04. At this time, the output of the C++ and Python tools are still windows specific. Over time, we will be updating the C++ tool to emit xplat C++. The Python projection depends on the C++ projection, so adding xplat support will be fairly easy once xplat C++ projection is available.

**Comment by devhawk** [comment]
#59 adds a bash script for building xlang. Tested on Ubuntu 18.04 (both WSL and native)

**Comment by nightlark** [comment]
Building on MacOS is rather painful -- Apple ships a version of libc++ with XCode that is missing experimental/filesystem in XCode 9 and 10, and that only has optional in XCode 10 (I think in 9 it might be experimental/optional).

So far I've tried using clang 6 and 7 installed using homebrew, but then I get errors such as `error: no member named 'visit' in namespace 'std'; did you mean simply 'visit'` and ` error: no template named 'is_enum_v' in namespace 'std'; did you mean 'is_enum'?`. It almost seems like maybe the copy of libc++ installed by the homebrew package is old.

**Comment by devhawk** [comment]
xlang has it's own visit function. I ran into the same issue you described getting xlang building on Ubuntu w/ clang 6. PR #48 included [explicitly specifying the visit function namespace](https://github.com/Microsoft/xlang/commit/5cef93cdb0b1832ecb5d0415241ba7887849023d#diff-a989e0b1c0c237cb7944939b3cb3a735R709). 

@nightlark would you mind checking the value of _LIBCPP_VERSION? It's declared in a file named [__config](https://github.com/llvm-mirror/libcxx/blob/release_60/include/__config#L36) in libc++. 

Also, we haven't begun work on getting xlang compiling on Mac. So major thanks for your help @nightlark!Any info you can give us about what you've tried and what works/doesn't work will save us time down the road. Feel free to add any details you can provide to this thread.

**Comment by devhawk** [comment]
Note, I changed the title because Unix build is working (PRs #48 and #61). 

If we need to make more changes to enable unix build, let's open a new issue so we can track it separately from Mac build.

**Comment by devhawk** [comment]
![harry_mac_mini](https://user-images.githubusercontent.com/8965/49311398-eb501a80-f495-11e8-8f98-98ff892e6ff3.jpg)

**Comment by kennykerr** [comment]
There are no plans to support MacOS at the moment.
