### ISSUE TITLE
cppwinrt_comp fails to find winmd's with "%" in their directory path

### ISSUE THREAD

**Issue by beaucha3** [microsoft/xlang#358]
Repro steps:
- Create a new C++/WinRT component project in Visual Studio, with the project root set to a folder that has a "%" character in its name.  Change no other project defaults.
- Press F5 to build.
- The build will fail on the cppwinrt_comp step with error code 3 (path not found).

**Comment by kennykerr** [comment]
Looks like msbuild can't find the cppwinrt compiler.

**Comment by kennykerr** [comment]
Moved to https://github.com/microsoft/cppwinrt/issues/366
