### ISSUE TITLE
Build instruction using GCC/MingW/Clang

### ISSUE THREAD

**Issue by udnaan** [Microsoft/xlang#36]
In order for this to be truly crossplatform, one should be able to build it using various compilers. This is just a placeholder to gauge interest and to mark the progress towards that. 

If that is already supported, than treat this as a request to update readme and to add travis/circleci builds using those toolchains. 

Have a good weekend.

**Comment by devhawk** [comment]
#59 adds a bash script for building on linux. Tested on Ubuntu 18.04 (both via WSL and native). 

Right now we are focusing on clang for Linux.

**Comment by udnaan** [comment]
Great thanks!

Although, I still can't access the build so I don't know how and what it does. It would be nice to have the CI be accessible.

**Comment by devhawk** [comment]
We don't have CI setup for Linux (yet!). #59 will include an updated /src/readme.md w/ Linux build instructions (I'm writing them now and will update PR before I go home for the day)

**Comment by devhawk** [comment]
#59 was closed in favor of #61, which added new build scripts and instructions. I'm closing this issue, but feel free to reopen or file a new one @udnaan if you're still having issues.
