### ISSUE TITLE
Decide on casing for interfaces.

### ISSUE THREAD

**Issue by manodasanW** [microsoft/xlang#363]
xlang_unknown uses pascal casing today.  While the other PAL functions use snake casing.  We should come to an agreement on what to use for interfaces and do that throughout.  We should also decide on how interfaces are named and how casing is for struct members.

**Comment by kennykerr** [comment]
Yes, this has been bothering me for a while. The PAL for the Windows Runtime (along with all APIs) uses `CapitalizedWords` for all names, functions, and interfaces. It's only the C++ language projection that uses `lower_case` for non-projected names. It does so to distinguish between the Runtime/APIs and the library support provided by C++/WinRT.

I would find it far less confusing if the xlang PAL used CapitalizedWords throughout. Typically, language projections hide the PAL anyway, so it should not affect any personal choice made by any particular language. It's also *very* **very** confusing to see COM interfaces that are named using lower_case.

**Comment by OneWingedShark** [comment]
There's only one solution: **ALL_UPPER_CASE**.
After all, it's not _real_ programming unless it looks like COBOL.
;)
