### ISSUE TITLE
Pythonic Python Experience

### ISSUE THREAD

**Issue by devhawk** [microsoft/xlang#37]
Currently, pywinrt (aka the python projection generation tool) emits code that is usable from python, but does not provide a pythonic experience - i.e. it does not feel natural and familiar to a python developer. This issue tracks the work we will do to generate a more pythonic experience by wrapping the generated native types in pure python.

At a minimum, expected to project the following WinRT constructs as the corresponding pythonic constructs:

| WinRT Construct   | Python Construct                        |
|-----------------  |-------------------                      |
| Namespaces        | pythonic experience TBD                 |    
| IStringable       | \_\_str__ support                       |
| IClosable         | with statement support                  |
| Collections       | sequence protocol and \_\_len__ support |
| IAsync*           | await support                           |
| get/put methods   | property support                        |
| add/remove methods | pythonic experience TBD                |

**Comment by nvictor** [comment]
so happy to see the wip of the python projection!
