### ISSUE TITLE
Select apartment type for pywinrt

### ISSUE THREAD

**Issue by zooba** [microsoft/xlang#370]
When I import `winrt`, an MTA is immediately initialized. This has two problems:
* when I import on a second thread, this code is not executed and the MTA is not initialized
* if I want an STA I have no way to create one

It should be possible to explicitly initialize a single-threaded apartment, and if I have not, then a multi-threaded apartment should be automatically initialized on first use.

**Comment by kennykerr** [comment]
The Python tool is no longer under active development, but feel free to contribute the feature you're after.

**Comment by bburky** [comment]
Please reopen this issue if [Python/WinRT is now under active development](https://github.com/microsoft/xlang/issues/634#issuecomment-631284342).
