### ISSUE TITLE
Registration-free WinRT components

### ISSUE THREAD

**Issue by Alovchin91** [Microsoft/xlang#373]
Hi guys,

I just wanted to share my excitement about the newly introduced Windows 10 1903 feature:

https://blogs.windows.com/buildingapps/2019/04/30/enhancing-non-packaged-desktop-apps-using-windows-runtime-components/

It's very cool to see that this idea made it into Windows release! I believe you and @kennykerr personally have influenced this decision, so

THANK YOU!

It's nice that WinRT idea lives and develops. Next stop - cross-platform Xlang!

Please feel free to close this issue as soon as you read it :)

<sub><sup>I have a small project enabling this idea for older versions of Windows, you might want to check it out: https://github.com/Alovchin91/WinRTDesktopInterop</sub></sup>

**Comment by kennykerr** [comment]
Thanks! We're pretty excited about this as well. 😉

**Comment by Alovchin91** [comment]
Small feedback: it would be nice if C++/WinRT Visual Studio extension didn't require an enormous UWP workload to install now :)

![image](https://user-images.githubusercontent.com/8490695/56991442-f370cb00-6b97-11e9-9031-90b84ecec9d1.png)

**Comment by kennykerr** [comment]
I hear you. 😉 Great feedback for the Visual Studio team. Here's where you can make your voice heard:

https://developercommunity.visualstudio.com/
