### ISSUE TITLE
cppwinrt crosscompiling from linux mingw to windows target

### ISSUE THREAD

**Issue by Alkeryn** [Microsoft/xlang#377]
So i would like to crosscompile a windows application from linux
because my linux dev environment is much more confortable and i want to build a crossplatform software that have its windows implementation and linux one using the preprocessor for optimal code reuse

Though i haven't found a way to compile winrt using software from linux (the runtime platform is still windows)

I want to use the editor i want to use (vim precisely) and not be forced to use visual studio, so is there a toolchain or anything to do

Also i rather use a simple and nice makefile than it being dependant on visual studio

I know there is the python winrt but i want to use c++ for performance reasons.

**Comment by kennykerr** [comment]
Sure, you can download the latest version of the [distribution package](https://www.nuget.org/packages/Microsoft.Windows.CppWinRT/) (which is just a zip file) that contains `cppwinrt.exe` and invoke that directly. The `cppwinrt.exe` tool has no dependencies of its own (and thus does not require Visual studio). You can simply use it to generate headers that you can then compile directly or via whatever build system you prefer.

**Comment by Alkeryn** [comment]
@kennykerr does it runs on wine ?
i want to crosscompile from linux ^

**Comment by kennykerr** [comment]
C++/WinRT itself only supports Windows. I have no experience with Wine or Linux. 

The xlang project aims to produce a cross-platform version of C++/WinRT that will run on Linux, but that is not yet ready.

The command line is pretty simple. Run `cppwinrt` without any arguments for a summary. For example:

```
cppwinrt -in <any number of winmd files> -out <location of generated headers>
```

**Comment by Alkeryn** [comment]
Thanks :)
it runs on wine so far
I don't want to run it on linux i just want to be able to build from linux because it is more confortable for me and that'll be quite a big project, but thanks :)

**Comment by kennykerr** [comment]
Sounds good. Enjoy!

**Comment by Alkeryn** [comment]
Yes i guess, where do i get those winmd file ?
(i'm not familiar with the windows dev ecosystem yet)

**Comment by kennykerr** [comment]
The winmd files describe the API surface of one WinRT component to another component or app that would like to make use of that component's functionality. Windows includes many APIs that are shipped and described using winmd files. You can find them in the Windows SDK or if you'd rather not install an SDK you can just point cppwinrt to the winmd files that ship with Windows in the c:\windows\system32\WinMetadata folder. If that's what you're after you can simply use the "local" shortcut as follows:

```
cppwinrt -in local 
```

**Comment by Alkeryn** [comment]
Well they aren't shipped with wine so i just copied them from windows
i'm going step by step to have a first working build haha
my current issue is that it can't find <experimental/coroutine>
Well i think i'll have a lot of things to do before being able to build from linux but that's a step ^

**Comment by kennykerr** [comment]
The latest version of Clang (libc++) and Visual C++ include that header. 

https://godbolt.org/z/KXfPEU

**Comment by Alkeryn** [comment]
Yup i copied the MSVC include and it worked
now it dosen't find <corecrt_terminate.h>
but i think i'm getting close haha

**Comment by Alkeryn** [comment]
Well i can't find a way to compile winrt project from linux and that's really annoying, i don't want to use visual studio.

**Comment by kennykerr** [comment]
You can compile using the command prompt with either Clang or Visual C++ (CL). No need to use Visual Studio, but then you're on your own trying to get those toolchains installed. VS Code is also quite a good alternative.
