### ISSUE TITLE
python winrt InputInjector.try_create() Runtime error

### ISSUE THREAD

**Issue by Alkeryn** [microsoft/xlang#380]
So i try to define a variable like this
`injecte = injecte = InputInjector.try_create()`
and i get this error
![image](https://user-images.githubusercontent.com/11599075/57054544-788dda00-6c95-11e9-8028-f2bb318c9d22.png)
most other commands seems to be working fine
Any idea ?

**Comment by Alkeryn** [comment]
![image](https://user-images.githubusercontent.com/11599075/57054602-d7ebea00-6c95-11e9-90fc-9fffbb66cdb0.png)
maybe has something to do with this idk

**Comment by devhawk** [comment]
Thanks for the bug report. I'm heading to pycon so I might not have much time to look at this until next week. Can you post your main.py, or at least enough code to repro the issue?

**Comment by Alkeryn** [comment]
@devhawk 
```python
import ctypes
from winrt.windows.ui.input.preview.injection import *
MessageBox = ctypes.windll.user32.MessageBoxW
# MessageBox(None, 'Hello', 'Window title', 0)
# injecte = InputInjector.try_create()
# print(dir(injecte))
pen = InjectedInputPenInfo()
pen.pointer_info.pixel_location.position_x = 2
pen.pointer_info.pixel_location.position_y = 2
pen.pressure = 0.43
pen.rotation = 0
pen.tilt_x = 0
pen.tilt_y = 0
# InputInjector.initialize_pen_injection(0)
print(dir(InputInjector))
# print(type(InputInjector.try_create))
# mmm=InputInjector.try_create
# print(mmm)
```
Also looks like most InputInjector function return this error 
![image](https://user-images.githubusercontent.com/11599075/57054775-fb636480-6c96-11e9-90ea-05c008e8ce93.png)
They exept an InputInjector object for some reason but in the official doc they take another type

**Comment by kennykerr** [comment]
Harry, "Call context cannot be accessed after call completed." is RPC_E_CALL_COMPLETE. This typically means a server is trying to impersonate a client but there is no client to impersonate.

**Comment by kennykerr** [comment]
The Python tool is no longer under active development. Let us know if this is still an issue, but my guess is that the Windows.UI APIs are not going to work from Python without substantially more development as they typically have deep dependencies on the app model that is probably not available in the Python environment out of the box.
