### ISSUE TITLE
How does the C++/CX TypeInformation change for C++/WinRT?

### ISSUE THREAD

**Issue by MRahilly** [Microsoft/xlang#381]
//TypeInformation^ typeInfo = ref new TypeInformation(colorsTypeName);
TypeInformation typeInfo { TypeInformation(colorsTypeName) }; // error: "TypeInformation undeclared identifier"

Should "xlang/src/library/meta_reader.h" be used in some way instead of TypeInformation?

**Comment by kennykerr** [comment]
Can you share a minimal self-contained repro? For example, I don't know what "TypeInformation" is.

**Comment by MRahilly** [comment]
Apologies. I should have written "TypeInfo" which seems to be a "Sytem.Reflection" type belonging to the .NET layer on WinRT. If so, is there an underlying type that could instead be accessed from C++/WinRT?

**Comment by kennykerr** [comment]
It depends on the API that you're trying to call. Hence, the request for a minimal self-contained repro. I suspect you can use `Windows::UI::Xaml::Interop::TypeName` but you'd have to check what API you're trying to call to see whether that is what it is expecting.

**Comment by MRahilly** [comment]
Thanks for that. To avoid building a C# DLL, I will translate the following C# code and include it as part of my C++/WinRT project which should give me the "TypeInformation" class that I need.

using System;
using System.Collections.Generic;
using System.Reflection;

namespace ReflectionHelper
{
    public sealed class TypeInformation
    {
        Type type;
        TypeInfo typeInfo;

        public TypeInformation(Type type)
        {
            this.type = type;
            typeInfo = type.GetTypeInfo();
        }

        public string Name
        {
            get
            {
                return type.Name;
            }
        }

        public bool IsPublic
        {
            get
            {
                return typeInfo.IsPublic;
            }
        }

        public bool IsSealed
        {
            get
            {
                return typeInfo.IsSealed;
            }
        }

        public TypeInformation BaseType
        {
            get
            {
                return new TypeInformation(typeInfo.BaseType);
            }
        }

        public IEnumerable<PropertyInformation> DeclaredProperties
        {
            get
            {
                IEnumerable<PropertyInfo> declaredProperties = type.GetTypeInfo().DeclaredProperties;

                foreach (PropertyInfo propertyInfo in declaredProperties)
                {
                    yield return new PropertyInformation(propertyInfo);
                }
            }
        }

        public IEnumerable<ConstructorInformation> DeclaredConstructors
        {
            get
            {
                IEnumerable<ConstructorInfo> declaredConstructors = type.GetTypeInfo().DeclaredConstructors;

                foreach (ConstructorInfo constructorInfo in declaredConstructors)
                {
                    yield return new ConstructorInformation(constructorInfo);
                }
            }
        }

        public bool IsAssignableFrom(TypeInformation derivedType)
        {
            return typeInfo.IsAssignableFrom(derivedType.typeInfo);
        }

        public PropertyInformation GetDeclaredProperty(string name)
        {
            return new PropertyInformation(type.GetTypeInfo().GetDeclaredProperty(name));
        }

        public override bool Equals(object obj)
        {
            if (obj == null || !(obj is TypeInformation))
                return false;

            return this.type.Equals((obj as TypeInformation).type);
        }

        public override int GetHashCode()
        {
            if (type == null)
                return 0;

            return type.GetHashCode();
        }
    }
}
