### ISSUE TITLE
cppwinrt Desktop console app - doesn't generate projection headers for cppwinrt references

### ISSUE THREAD

**Issue by mediabuff** [microsoft/xlang#387]
I first tried, adding cppwinrt dll project as reference,  VS wouldn't let me add - saying different platform or something equivalent.

Next, I am trying add the *.winmd file generated by the cppwinrt dll project. Was able to add. But no generated files when I compile. 

Using the latest versions of cppwinrt package.

**Comment by Scottj1s** [comment]
Please see:
[Referencing a UWP component project from a Native app to create a projection](../wiki/Referencing-a-UWP-component-project-from-a-Native-app-to-create-a-projection)

**Comment by mediabuff** [comment]
thank you. Just saw the post on regfree winrt. Great! Will try the VS workaround.
