### ISSUE TITLE
Generated sources from IDL always pass arguments by const ref

### ISSUE THREAD

**Issue by tim-weis** [microsoft/xlang#388]
Using the VSIX (2.0.190425.5) to process IDL files produces sources with declaration and definition stubs, always passing arguments by const ref. This is generally fine, unless you are authoring an async method, e.g.
```
namespace ns
{
    runtimeclass Settings
    {
        Windows.Foundation.IAsyncAction SetTimeUtc(Windows.Foundation.DateTime UtcTime);
    }
}
```
produces this header:
```
namespace winrt::ns::implementation
{
    struct Settings : SettingsT<Settings>
    {
        Settings() = default;

        Windows::Foundation::IAsyncAction SetTimeUtc(Windows::Foundation::DateTime const& UtcTime);
                                                                                     // ^ ouch
    };
} 
```
causing a subtle bug waiting to happen. Async functions should always pass by (const) value instead, and the generated stubs should honor this.

This seems to be somewhat related to #384, which apparently does the opposite. Maybe this is an opportunity to consolidate the source generation into a single implementation.

**Comment by kennykerr** [comment]
Thanks for the report Tim. That's a regression as it should already be doing that.
