### ISSUE TITLE
Allow source stubs to get generated from IDL without a full compile

### ISSUE THREAD

**Issue by tim-weis** [microsoft/xlang#389]
When authoring a Windows Runtime type the workflow<sup>1</sup> currently is:

* Edit the IDL file.
* Compile the project (and wait for the compiler to issue errors).
* Copy code from the generated sources.
* Compile again.

This is tedious. *"Compile"* (or <kbd>Ctrl</kbd>+<kbd>F7</kbd>) is available from the context menu of any IDL file. Invoking it does process the IDL file, too, but it won't generate sources. Is it possible to get the sources generated as part of 'compiling' just that file, without a full compile? This would certainly make for a smoother workflow.

---

<sup>1</sup> *Using Visual Studio and the VSIX (2.0.190425,5).*

**Comment by BrentRe** [comment]
This is a great suggestion. We'll see what's needed to make this work.

**Comment by Scottj1s** [comment]
Unfortunately, an mdmerge operation is required after midl runs and before cppwinrt runs.  This is a definite bottleneck in the process and we're working with the Visual Studio team to optimize that workflow.
