### ISSUE TITLE
Matching C++/WinRT samples for the C++/CX samples now on MSDN

### ISSUE THREAD

**Issue by MRahilly** [microsoft/xlang#400]
When might we expect to see these?

**Comment by kennykerr** [comment]
@oldnewthing has already started porting a few of the samples. He can provide more info on where to find those.

**Comment by kingofthebongo2008** [comment]
@MRahilly
Do you have something specific in mind?
Most samples are easily reconstructed. 
I am just curious

**Comment by oldnewthing** [comment]
They are in the [UWP samples repo](https://github.com/Microsoft/Windows-universal-samples/) in directories named `cppwinrt`. Available now:  AppWindow, BluetoothLE, FileAccess, FilePicker, FileSearch, FileThumbnails, FolderEnumeration, FullScreenMode, JumpList, MultipleViews, ResizeAppView, TitleBar. Up next: DeviceEnumerationAndPairing. Is there a specific sample you want to see ported?

**Comment by mediabuff** [comment]
how about https://github.com/clarkezone/UWPCompositionDemos/tree/master/MediaPlaybackViews
This is a sophisticated example - multiple view and threads - having trouble with function:

private async void openpopupplayer_click(object sender, RoutedEventArgs e)
        {
            PopupPlayer newPlayer = null;
            CoreApplicationView newView = CoreApplication.CreateNewView();
            var newViewId = 0;
            await newView.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
            {
                newPlayer = new PopupPlayer();
                Window.Current.Content = newPlayer;
                Window.Current.Activate();
                newViewId = ApplicationView.GetForCurrentView().Id;

                var player = ((App)Application.Current).Player;
                newPlayer.SetPlayer(player);

                newPlayer.HoookVideo();
            });

            var viewShown = await ApplicationViewSwitcher.TryShowAsViewModeAsync(newViewId, ApplicationViewMode.CompactOverlay);
        }

**Comment by kennykerr** [comment]
@clarkezone do you have a C++ version of this sample?

**Comment by MRahilly** [comment]
I would like to see the samples from Petzold PW6 translated to C++/WinRT. I think this could have the same effect as the second edition as the Petzold book in 1990 sparking off a chain reaction and populating the Windows Store with a festoon of apps.

**Comment by MRahilly** [comment]
Thanks Raymond for the UWP samples repo. Until recently I could find only C++/CX samples.

**Comment by oldnewthing** [comment]
@mediabuff You'll have to ask the owner of that repo for a C++/WinRT translation. The repo I run is the [UWP samples repo](https://github.com/Microsoft/Windows-universal-samples/).

**Comment by oldnewthing** [comment]
Here's a literal translation. It could be made more idiomatic.

```C++
winrt::fire_and_forget openpopupplayer_click(IInspectable const&, RoutedEventArgs const&)
{
    auto lifetime = get_strong();
    PopupPlayer newPlayer{ nullptr };
    CoreApplicationView newView = CoreApplication::CreateNewView();
    auto newViewId = 0;
    co_await resume_foreground(newView.Dispatcher());

    newPlayer = PopupPlayer();
    Window::Current().Content(newPlayer);
    Window::Current().Activate();
    newViewId = ApplicationView::GetForCurrentView().Id();

    auto player = Application::Current().as<App>().Player();
    newPlayer.SetPlayer(player);

    newPlayer.HoookVideo();

    co_await resume_background();

    auto viewShown = co_await ApplicationViewSwitcher::TryShowAsViewModeAsync(newViewId, ApplicationViewMode::CompactOverlay);
}
```

**Comment by mediabuff** [comment]
@oldnewthing  - thank you. Finally, I got that sample working in cppwinrt. Just for my education, could you please explain why we need
1) auto lifetime = get_strong(); at begining
2) and  co_await resume_background(); at the tail end.

**Comment by oldnewthing** [comment]
The `get_strong()` is to prevent the `this` object from being destructed while a coroutine is still running.

The `co_await resume_background();` is a literal translation of the end of the lambda passed to `newView.Dispatcher.RunAsync`. It is almost certainly not actually necessary.

**Comment by mediabuff** [comment]
On the second point, shouldn't it be be ?

```
auto prevDispatcher = Dispatcher();
auto lifetime = get_strong();
...
...
co_await resume_foreground(prevDispatcher );
```

**Comment by oldnewthing** [comment]
Looks like you're right. I didn't really look closely to see what thread the code was starting from. Looks like it's starting from a UI thread. You don't need to keep the previous dispatcher. You can just call `Dispatcher()` to get the page's dispatcher (which will be the one that is active when the `Click` event is raised.

I think this issue should be closed because it's not an xlang issue.
