### ISSUE TITLE
Is metadata generation from IDL within the remit of xlang?

### ISSUE THREAD

**Issue by MarkIngramUK** [microsoft/xlang#405]
Currently it seems like xlang is to be used after the metadata has already been generated (via a tool such as [midlrt](https://docs.microsoft.com/en-us/windows/desktop/midl/midlrt-and-windows-runtime-components)). This is fine on Windows where the tool exists, but what's the solution for authoring APIs on other platforms? Will future xlang support generation of metadata, or will it always require another tool?

**Comment by devhawk** [comment]
We are working on a xplat tool for metadata generation. @kythant is doing most of the work in a topic branch. #401 is a current PR into that topic branch.

**Comment by BenJKuhn** [comment]
Just to clarify on Harry's response: The xlang repo contains some tooling that supports the winrt type system, and some tooling that supports the xlang type system. The two are similar but distinct. The IDL tool currently being created will support the xlang type system, _not_ the winrt type system. 

The MIDL / MIDLRT will continue to be the definitive tool for creating WinRT types. That tool contains deep knowledge of the WinRT type system that we are not re-creating in the xlang repo at this time including contract version migration, deep understanding of numerous attributes, etc. The xlang tool will also not support the original pre-IDL3 WinRT syntax, which is far more verbose and complex to deal with. 

While it would be great to have a portable tool for creating WinRT types, we have no time frame for creating such a tool.

Ben

**Comment by MarkIngramUK** [comment]
Thanks for the response, just for clarification, it is the non-WinRT IDL tooling that I was interested in.
