### ISSUE TITLE
C++/WinRT should handle disconnected async completion handlers much like it does event handlers

### ISSUE THREAD

**Issue by kennykerr** [microsoft/xlang#409]

**Comment by oldnewthing** [comment]
Details: When invoking event handlers, C++/WinRT [checks for well-known error codes](https://github.com/microsoft/xlang/blob/e655fd0ad64298e576c4e19ecfa16c3f9745f9cd/src/tool/cppwinrt/strings/base_events.h#L461), which handles cases where the event handler was disconnected. However, the invoke of the async operation completed handler contains no such checks.
