### ISSUE TITLE
wrong form of #include is used for g.h and .g.cpp, should use <> form.

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/xlang#413]
In the generated implementation code (`/Generated Files/source`) the #includes that access the .g.h and .g.cpp files use the `""` form. This is incorrect as it indicates these files might be located next to the file including them but they are not. They are intended to be found by searching the INCLUDES path. This only works due to something putting `.` on the INCLUDES path (that is a bug or questionable behavior in itself).

`#include "Sample.Singleton.g.h"`

should be

`#include <Sample.Singleton.g.h>`

**Comment by kennykerr** [comment]
Can you share a minimal standalone repro where this fails? This is not my experience, but if you really want <> rather than "" you can use the -brackets option and you'll get angle brackets for all generated includes.

**Comment by ChrisGuzak** [comment]
nothing fails. this is just tracking the semantics of `<>` vs `""`. the former only searches the INCLUDES path, the later only looks in the current directory (relative to the component that included).

I find this distinction important to maintain as it indicates the origin of the files, within your project or outside of it.

**Comment by kennykerr** [comment]
Both forms will search the include path. The only difference I know of is that <> will not look in the current directory.

**Comment by kennykerr** [comment]
Closing this as there is no clear right/wrong answer here. The default is `""` but you can get `<>` by using the `-brackets` option so you are in complete control. Changing the default seems like an unnecessary breaking change.
