### ISSUE TITLE
Focus should move back to cppwinrt - make it robust before xlang.

### ISSUE THREAD

**Issue by mediabuff** [microsoft/xlang#414]

**Comment by kennykerr** [comment]
Our focus has not shifted away from C++/WinRT. The team remains committed to C++/WinRT and I'm personally still very passionate about its ongoing development. We have grown the team, notably with the addition of @devhawk whose focus is on cross-platform, but this does not mean that we are placing less emphasis on C++/WinRT.

If you have specific concerns about C++/WinRT's robustness, please share a minimal self-contained repro and we can certainly take a look.

**Comment by mediabuff** [comment]
Kenny, thanks for your reply. It's less about individual code snippets - which cppwinrt seem to be doing fine. It's the whole toolchain, artifacts management, productivity , design and compile times. MS should really take a medium size app - say BuildCast as an example - and go through the pains of porting it. Not just making work but undrestand the pains and how the toolchains work or not work together. This platform is still at proof of value stage - and seems to be a long way to be less than a glorified header file.

**Comment by kennykerr** [comment]
Good feedback. We are actually doing that kind of work behind the scenes to both validate its effectiveness in the larger toolchain and impact on dev inner loop. We do in fact spend a great deal of time on that, including porting some high-profile apps. We also use C++/WinRT *very* heavily inside the Windows core operating system, which has put an amazing amount of pressure on the project to perform at scale and all of that experience is what is feeding back into the work the team is doing to improve C++/WinRT from one update to the next. We also continue to work with the Visual Studio team to improve integration. Do have a look at [our recent Build talk](https://www.youtube.com/watch?v=X41j_gzSwOY) where we highlight some of these improvements. And we're certainly not done yet.

**Comment by mediabuff** [comment]
Please try this simple sample - straight from your Docs - https://github.com/coderox/BgLabelControlApp.

Delete the generated files in the repo and build under the newest versions of cppwinrt. Can't seem to get it to work. Few problems encountered

`1. I had add #include "BgLabelControl.h" in "App.h" - is this required in all cppwinrt apps - to include all control headers in "App.h`

2. Once I get past that, I added the BgLabelControl to main.xaml. 
```
BgLabelControlApp\MainPage.xaml(12,47): XamlCompiler error WMC0075: Missing Content Property definition for Element 'BgLabelControl' to receive content 'This is a test'
gLabelControlApp\MainPage.xaml(12,47): XamlCompiler error WMC0011: Unknown member '_UnknownContent' on element 'BgLabelControl'
```

**Comment by mediabuff** [comment]
```
<Page
    x:Class="BgLabelControlApp.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:BgLabelControlApp"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button x:Name="myButton" Click="ClickHandler">Click Me</Button>
        <local:BgLabelControl>This is a test</local:BgLabelControl>
    </StackPanel>
</Page>
```

**Comment by mediabuff** [comment]
Two other issues reported in https://github.com/microsoft/xlang/issues/431 and https://github.com/microsoft/xlang/issues/430
