### ISSUE TITLE
CppWinRTOptimized is not documented

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/xlang#415]
This .vcxproj property enables cppwinrt.exe `-opt` but it is not mentioned in the docs.

Seems that should go here:
https://github.com/microsoft/xlang/blob/d7e00e126fe7727df59ec31a91db5a2fd11bc140/src/package/cppwinrt/nuget/readme.md#customizing

**Comment by Scottj1s** [comment]
Added the table entry, assigning to Kenny to add a hyperlink to blog post, msdn doc, etc
