### ISSUE TITLE
C++/WinRT -optimize fails to call through factory

### ISSUE THREAD

**Issue by kennykerr** [microsoft/xlang#418]
The -optimize flag causes a .g.cpp file to be generated that enables the projection to call directly into the implementation. However, it should be calling into the factory rather than the class to enable factory implementations to be used. The factory always forwards to the class (by default) so it would in no way prevent existing usage nor would it impact performance since it is all inlined.

**Comment by kennykerr** [comment]
Had a closer look at this and it is not *all* inlined. I’m inclined to “won’t fix” this. Searching the OS repo it is exceedingly rare to have an implementation that uses static_lifetime and thus requires an implementation within the factory itself. 

The reason I’m reluctant to do so is because the -optimize behavior only works as well as it does because it does not have to go through the factory at all. Although the factory cache is blazingly fast compared to RoGetActivationFactory, it is not exactly fast compared to a local function call and -optimize gives you that level of call efficiency. And calling make<T> on the factory just to make the call is also another big speed bump.

The workaround is pretty simple and I'll document that. Briefly, the class static simply needs to call back into the factory to ensure that factory static lifetime state is employed for something like a static singleton implementation.

**Comment by ChrisGuzak** [comment]
here is the work around for others to copy
```cpp
namespace winrt::Windows::Prototypes::implementation
{
    // This method exists to enable the cppwinrt.exe -opt .g.cpp generated to call.
    // It is not needed for clients of the factory object.
    //
    // The implementation must come after the declaration to break the circular dependency
    // between the implementation and factory_implementation classes.
    Windows::Prototypes::Singleton Singleton::Current()
    {
        return make<factory_implementation::Singleton>().as<ISingletonStatics>().Current();
    }
...
```

**Comment by oldnewthing** [comment]
Improved workaround enabled by microsoft/cppwinrt#589:

```cpp
namespace winrt::Windows::Prototypes::implementation
{
    // This method exists to enable the cppwinrt.exe -opt .g.cpp generated to call.
    // It is not needed for clients of the factory object.
    //
    // The implementation must come after the declaration to break the circular dependency
    // between the implementation and factory_implementation classes.
    Windows::Prototypes::Singleton Singleton::Current()
    {
        return make_self<factory_implementation::Singleton>()->Current();
    }
}
```
