### ISSUE TITLE
Create a C++ /WinRT static library project template type

### ISSUE THREAD

**Issue by BenJKuhn** [microsoft/xlang#419]
Migrating this from an issue reported in Windows Feedback Hub. People have worked around this issue and figured out how to do it, but requires a bit of reverse engineering to get the startup code out of the way, etc.

**Comment by kennykerr** [comment]
Great idea.

**Comment by kennykerr** [comment]
It turns out that it's trivial to use the built-in static lib project and add a reference to the C++/WinRT NuGet package and off you go. I'm going to close this unless there's a compelling case for maintaining a dedicated project template.
