### ISSUE TITLE
pass winrt::weak_ref between implementation classes

### ISSUE THREAD

**Issue by mediabuff** [microsoft/xlang#420]
I would like have one implementation class hold a weak reference to another. Can't seem to get this pattern work. 
```

// ClassB.h

struct ClassA // forward declare. Can't include "ClassA.h" - will lead to circular refernce
struct ClassB
{
	void setClassA(winrt::weak_ref<winrt::implementation::ClassA> classA);  
	
	// Compile error forward declare does'nt work
	// error c2139: an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_base_of'
}

// ClassA.cpp

void ClassA::OnPropertyChanged(DependencyPropertyChangedEventArgs const& e)
{
	auto classB = e.NewValue().try_as<ClassB>();
	if (classB)
	{
            // Option A
	   classB->setClassA(get_weak());

            // Option B
            classB->setClassA(this);
	}
}
```

**Comment by kennykerr** [comment]
Yes, this is a limitation. The weak_ref uses type traits to figure out how to retrieve the weak reference itself and this requires the complete definition of the type. Thanks for the feedback. I'll see what we can do to improve this.

**Comment by kennykerr** [comment]
Detecting that a weak reference to an implementation should be created requires knowledge of the type that prevents forward declaration. Given that there are other ways to solve this problem, I'm going to leave this as is for now. Here's one solution: 

https://gist.github.com/kennykerr/9f7ad000c8021cbe2d9f32727b9de901
