### ISSUE TITLE
nuget README.md is missing documentation on CppWinRTOptimized

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/xlang#426]
Documentation on this:

https://github.com/microsoft/xlang/blob/6f7daac42cef2063b507605e691c1799ebd54a88/src/package/cppwinrt/nuget/Microsoft.Windows.CppWinRT.targets#L261

probably belongs here:

https://github.com/microsoft/xlang/blob/6f7daac42cef2063b507605e691c1799ebd54a88/src/package/cppwinrt/nuget/readme.md#L66-L68

**Comment by DHowett-MSFT** [comment]
Aaand that's a duplicate of #415. Sorry!

**Comment by rosca** [comment]
This was closed as a duplicate, but the Fast Abi option (CppWinRTFastAbi) is still not documented, and I could not find much info on the internet about it. Can you add some more information in the readme, or links to some external docs?
