### ISSUE TITLE
Performance of IXlangObject information

### ISSUE THREAD

**Issue by EliasAE** [microsoft/xlang#429]
The [XDN05](https://github.com/microsoft/xlang/blob/master/design_notes/XDN05%20-%20xlang%20Binary%20Interface.md) design note provides a definition of the `IXlangObject`, which focuses on the `GetObjectInfo` method for most of the information that can be extracted from all `IXlangObject` instances: “For xlang, instead of individual property get methods, IXlangObject exposes a single GetObjectInfo method.”

The design note provides two reasons for this approach:

* Considering that additional information categories may be added in the future, and not all information categories may be implemented by a given object: “Because enumerations can be additively versioned over time, it is possible to add new ones over time.”
* The intent to keep the virtual function pointer table small for objects: “Furthermore, it reduces the size of the virtual function table that every xlang object needs to support.”

In this issue I explore the trade-offs of this design choice and propose a better way of achieving this.

# Compared Approaches

I have analysed the following alternatives for implementing the above feature:

* __Option 1:__ The current proposed method: using one function on the `IXlangObject` interface, with a method that takes an enum value to indicate what operation is intended.
* __Option 2:__ Using individual methods in an interface, where a future new set of information types are added as a separate interface each time.
* __Option 3:__ Using individual methods in an interface, where a future new set of information types are added as a derived interface from the previous version of the interface.

Below I analyse the impact of each of these three choices given the above stated goals.

# Extensibility
All of the approaches allow for new members to be added without breaking existing objects. In the case of Option 1, this is achieved that old objects continue to return `false` for enum values that are not recognised. For option 2 and 3, this is achieved by `QueryInterface` returning an error for the additional interfaces.

# Execution Performance

Based on my benchmarks so far, the execution performance is along the following lines, compared to the performance of Option 1. 

Option | Execution Time
------|--------------------
Option 1 | base
Option 2 | 1% faster
Option 3 | 5% faster

![ExecutionSpeed](https://user-images.githubusercontent.com/47688036/58366872-49ebd380-7ed0-11e9-8c8f-4a142f991301.png)

The benchmarks were done with two versions of the interface, each with 3 methods. In each iteration one object was selected at random, and one method invoked on that object.
Based on these measurements, I don’t see a reason for Option 1 based on execution performance.

# Marshalling

Marshalling can be important when method invocation on objects are made across thread context, to out-of-process objects, or possible even remote objects. Even though xlang may not support those features at the moment, it is a severe limitation to design the core of the ABI without the possibility to extend with marshalling in the future.

The `GetObjectInfo` method returns generic data, which means that the marshaller has no way of knowing how the marshall the memory across apartment/process boundary. I consider the alternative to encode the marshalling behaviour of each individual enum value independently violates the layering, where the type system should provide the necessary information to the marshalling layer, not require the marshalling layer to be coded specifically for each method.

Therefore, I consider that `GetObjectInfo` would need to make sure that the void** info always points to memory allocated by `XlangMemAlloc`, to enable consistent marshalling. This creates unnecessary memory allocations for enum value that return scalar values, such as `ObjectSize`. As the intention of `ObjectSize` is to inform memory management in the client, this could have a performance impact.

Instead, Option 2 and Option 3 provide all the necessary type information in the interface specification for the marshaller to work without any specific considerations.

The benchmarks in the other sections has not taken this extra work into consideration. In case they did, I would expect Option 1 to have lower performance.

Based on this, Option 2 and Option 3 provides more benefit from a marshalling perspective compared to Option 1.

# Storage Size

One of the arguments for this design approach was the virtual function table size. In most cases, the virtual function table is stored in the executable as read-only and shared for all objects of a specific class or interface. In the benchmarks, I have compared the virtual function table size, but also considered the code size, as Option 1 has some extra instructions to dispatch each method call according to the enum value. 

Option | Storage Size
--------|--------------
Option 1 | base
Option 2 | 0% smaller
Option 3 | 3% smaller

![StorageSize](https://user-images.githubusercontent.com/47688036/58366881-5c660d00-7ed0-11e9-8450-58b9079a629f.png)

Based on these measurements, Option 3 would provide for the most compact executable, taking into account both virtual function table size and code size.

# Object Size

Another concern is the size of an instance of the object, as additional implemented interfaces are often implemented with several virtual function pointers in the object. Please see below for the impact on object size for each option:

Option | Object Size Impact (x64)	
--------|----------------------------
Option 1 | 8 bytes
Option 2 | 8 bytes + 8 bytes for each new interface version
Option 3 | 8 bytes

Option 2 has an impact on the object size, because it implements two (or more) versions of the interface. Option 1 and Option 3 is equivalent in terms of code size, independent of number of versions of the interface.

# Conclusion
Taking into consideration all of the above, I propose to use Option 3 for `IXlangObjet` instead. That is, that the `GetObjectInfo` is removed from `IXlangObject` and replaced with individual functions, such as `GetTypeName`, `GetHashCode`, `GetStringRepresentation`, `GetObjectSize`, etc.

If additional functions should be added in the future, I would propose that an additional IXlangObject2 interface is created which inherits from `IXlangObject` and adds additional methods. Although an object can select which version of the interface to support, I also propose each method must return a `XlangResult` and that clients are required to handle a return value `Xlang_NOTIMPL`, which makes sure that each object does not have to implement all of the methods in case an object just want to implement some of the methods in a particular version of an interface.

Let me know your thoughts or if I missed any consideration of IXlangObject’s design.

**Comment by Scottj1s** [comment]
@EliasAE, apologies for the tardy response.  Really appreciate the thorough analysis on this.  The team is still assimilating your input, but I think there's general agreement with your conclusions.  I expect that [XDN05](https://github.com/microsoft/xlang/blob/master/design_notes/XDN05%20-%20xlang%20Binary%20Interface.md) will be updated based on your recommendations.
