### ISSUE TITLE
static property stub generated both in *.g.cpp and *.cpp 

### ISSUE THREAD

**Issue by mediabuff** [microsoft/xlang#433]
```
	// ClassA.idl
	namespace myNameSpace
	{	
		runtimeclass ClassA : Windows.UI.Xaml.Controls.Control
		{
			ClassA();

			static Windows.UI.Xaml.DependencyProperty IsMutedProperty{ get; };
		}
	}
	
	// ClassA.g.cpp
    Windows::UI::Xaml::DependencyProperty ClassA::IsMutedProperty()
    {
        return myNameSpace::implementation::ClassA::IsMutedProperty();
    }
    
    
    //  ClassA.cpp from "generated\sources"
    Windows::UI::Xaml::DependencyProperty ClassA::IsMutedProperty()
    {
        throw hresult_not_implemented();
    }
```

The implementation should be in "sources" only, not in *.g.cpp

Related issues: https://github.com/microsoft/xlang/issues/414

**Comment by kennykerr** [comment]
This is actually correct. I'm going to publish an article on -optimize soon but this is an optimization that is well worth it. Briefly, the .cpp file is the skeleton implementation you may copy to your project to use as a starting point. The .g.cpp is what you include in your implementation when compiling with -optimize to light up inlined constructors and statics.

**Comment by mediabuff** [comment]
Thanks Kenny. I understand the point about the the skeleton implementation point. I assume the skeletons should compile at set go. The question was should this be on the "implementation" file or the *.g.cpp file.

**Comment by kennykerr** [comment]
The .cpp files contain methods generated in the implementation namespace (that throw) whereas .g.cpp contain methods generated in the projected namespace that forward to the implementation namespace.

**Comment by mediabuff** [comment]
Got it. thanks
