### ISSUE TITLE
defining a destructor for cppwinrt objects

### ISSUE THREAD

**Issue by mediabuff** [microsoft/xlang#454]
I am trying to track down a memory leak. To do this I am trying to define a destructor in my object and set a break point at the destructor to view the stack track - detecting who is actually deleting.

But winrt "implements" based classes don't allow destructors.  Can't seem to do like this example https://github.com/microsoft/xlang/blob/7176cb7dfd76ac1dd26c430095f63516c91f2822/src/tool/cppwinrt/test/no_make_detection.cpp

'winrt::impl::heap_implements<D>::~heap_implements' cannot override 'winrt::ABC::implementation::ClassA::~ClassA'

**Comment by kennykerr** [comment]
Your implementation may have a destructor - the requirement is simply that it be a public destructor.

**Comment by mediabuff** [comment]
Thank you Kenny. Great!!
