### ISSUE TITLE
Move XamlMetaDataProvider.cpp out of CppWinRTAddXamlMetaDataProviderIdl target

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/xlang#456]
Some builds execute in multiple passes, with IDL and C++ compiled independently.  This causes XamlMetaDataProvider.cpp not to be compiled.  The solution is to move the ClCompile entry outside of the CppWinRTAddXamlMetaDataProviderIdl target with something like this:
```
 
  <ItemGroup Condition="Exists('$(GeneratedFilesDir)XamlMetaDataProvider.cpp')">
    <ClCompile Include="$(GeneratedFilesDir)XamlMetaDataProvider.cpp" />
  </ItemGroup>

```

**Comment by jevansAN** [comment]
Looks like the rest of Scott's comment didn't survive - but could this be related to the XamlMetaDataProvider problem that is preventing store certification for cppwinrt apps? That is discussed in the following link https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/36126184-cannot-submit-app-to-the-store-using-cppwinrt-and#comments - haven't been able to find a solution even using the latest cppwinrt release.

**Comment by kennykerr** [comment]
The mildrt bug related to the DefaultOverloadAttribute attribute has been fixed as of build 18310 of the Windows SDK.

**Comment by Scottj1s** [comment]
(updated original post to show markup)

**Comment by kennykerr** [comment]
Moved to https://github.com/microsoft/cppwinrt/issues/369
