### ISSUE TITLE
module.g.cpp containers unreferenced formal parameter when generating with no statics.

### ISSUE THREAD

**Issue by aeloros** [microsoft/xlang#463]
When no statics are used the code generated for winrt_get_activation_factory() inside of module.g.cpp declares a parameter and never uses it.  This results in C4100 at compile time.

module.g.cpp(17) : error C4100: 'name': unreferenced formal parameter

example codegen:
void* WINRT_CALL winrt_get_activation_factory(std::wstring_view const& name)
{
    auto requal = [](std::wstring_view const& left, std::wstring_view const& right) noexcept
    {
        return std::equal(left.rbegin(), left.rend(), right.rbegin(), right.rend());
    };

    return nullptr;
}

**Comment by kennykerr** [comment]
This means your component doesn't implement any WinRT activation factories. I can silence the warning, but there's no point compiling `module.g.cpp` in this case.

**Comment by aeloros** [comment]
I think there is still value in compiling it, as it allows for infrastructure to be implemented up front to allow for organic component growth.  The fact that the linker will opt:ref it out should be benign enough.

**Comment by kennykerr** [comment]
Sure, happy to silence the warning. 👍
