### ISSUE TITLE
When support FaceAnalysis and SpeechSynthesis?Is there a plan?

### ISSUE THREAD

**Issue by 651778286** [microsoft/xlang#496]
SpeechRecognition,SpeechSynthesis and FaceAnalysis can provide AI capabilities,so it's something to look forward to

**Comment by kennykerr** [comment]
The xlang project is not the home of any particular API but rather the technology that such APIs are built with (e.g. C++/WinRT). For platform capability requests I suggest you submit feedback here:

https://wpdev.uservoice.com/
