### ISSUE TITLE
How to enable DLS synth on C++/winrt UWP app?

### ISSUE THREAD

**Issue by jevansAN** [microsoft/xlang#498]
I make use of winrt::Windows::Devices::Midi in my UWP app, and the Microsoft.Midi.GmDls device shows up in the output list and works fine, at least on the desktop Win10 machine used for development. It does not work on the Surface Go, apparently, and the app crashes at launch on the Go. I don't want to turn off S mode on the Go so I can't put VS on it to examine t his. I'm wondering if I have missed something that needs including. In order to make this work on the desktop I manually edited the project file, adding an item group for SDKReference Include="Microsoft.Midi.GmDls, Version=10.0.17763.0"
Is a manual edit of the project file really the right way to include this capability? I can't find any other place in the project settings or manifest that mentions it. If there is a better way to add MIDI and synth capabilities maybe that would explain the failure on the Surface Go.

**Comment by kennykerr** [comment]
This is a question about a specific API not directly connected with xlang. You're better off posting this question on stackoverflow.com
