### ISSUE TITLE
Unable to implement classic COM type using winrt::implements

### ISSUE THREAD

**Issue by sylveon** [microsoft/xlang#508]
In the version of C++/WinRT that is part of the Windows SDK, the following code in which I am using C++/WinRT to provide me an implementation of IUnknown compiles correctly:

```cpp
class AppVisibilitySink : public winrt::implements<AppVisibilitySink, IAppVisibilityEvents> {
private:
	std::function<void(bool)> m_startOpenedCallback;

public:
	inline AppVisibilitySink(std::function<void(bool)> startOpenedCallback) :
		m_startOpenedCallback(std::move(startOpenedCallback))
	{ }

	IFACEMETHODIMP LauncherVisibilityChange(BOOL currentVisibleState) override
	{
		try
		{
			m_startOpenedCallback(currentVisibleState);
			return S_OK;
		}
		catch (...)
		{
			return winrt::to_hresult();
		}
	}

	IFACEMETHODIMP AppVisibilityOnMonitorChanged(HMONITOR, MONITOR_APP_VISIBILITY, MONITOR_APP_VISIBILITY) override
	{
		return S_OK;
	}
};
```

I am now trying to write some pages in XAML to host in XAML Islands, so I was automatically upgraded to the NuGet version of C++/WinRT by Visual Studio. That code (among other) doesn't compiles anymore, because of the `override` specification on the functions. The compiler is saying that I did not override any base class method. After being clueless and removing the `override` to see if I can get more info, I get a (not really) better insight into the error:
![image](https://user-images.githubusercontent.com/6440374/60936776-4fdd1e80-a29c-11e9-8283-36645bd32406.png)

**Comment by kennykerr** [comment]
The trick is that you need to include `Unknwn.h` before any C++/WinRT headers to enable COM interop support. For example:

```C++
#include <Unknwn.h>
#include "winrt/Windows.Foundation.h"
```

Since C++/WinRT has no dependency on the Windows SDK, it has no way of knowing that you would like to implement COM interfaces that rely on the definition of `IUnknown` as defined by the Windows SDK.

**Comment by sylveon** [comment]
Thanks, issue resolved. Header inclusion order in another file that included this one is what had broke it.
