### ISSUE TITLE
CppWinRT NuGet now only supports VS 2019 - should be documented

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/xlang#514]
With some recent clang conformance work, the coroutine feature detection is now based on the macro __cpp_coroutines, which is defined when compiling with /await.  But this is not supported by VS 2017.  Users should be informed of that breaking change (msdn, nuget, etc).  Future breaking changes should follow semantic versioning rules (major version bump)

**Comment by tim-weis** [comment]
What's the final version of the NuGet package that still supports VS 2017? I believe it's 2.0.190620.2, but I would like confirmation on that.

The specific reason for me to maintain VS 2017 compatibility is that I'm supporting Windows 10 Mobile. While it's possible to publish AppX packages built with VS 2019, I still need VS 2017 to locally deploy and debug applications. This feature is no longer available in VS 2019, and I'm not aware of an (easy) way to deploy/debug a VS 2019 build using VS 2017.

**Comment by kennykerr** [comment]
That's correct. C++/WinRT 2.0.190620.2 supports VS 2017. The next update introduced additional standard conformance to ensure compatibility with Clang and VS 2019.

**Comment by Scottj1s** [comment]
Restored support for coroutine detection in VS 2017, closing this issue
