### ISSUE TITLE
26444 Avoid unnamed objects warning for Async actions

### ISSUE THREAD

**Issue by jevansAN** [microsoft/xlang#515]
Recently Visual Studio has begin putting up a warning, "26444 Avoid unnamed objects with custom construction and destruction (es.84)" in cases like the following: Suppose a class, MyClass, has a method declared as IAsyncAction GetStuff(), which uses a co_await for some purpose, e.g. co_await someStorageFolder.GetFolderAsync(L"folderName").
In that case, calling myClassInstance->GetStuff() will produce the warning. The warning is apparently associated with ignoring the return result of a method. But in the case of an AsyncAction we don't explicitly pay attention to the result, right? Or is this warning exposing an error that I should not ignore?
    ``

**Comment by kennykerr** [comment]
The warning is by design. You are ignoring the result of a function that returns an object with potentially expensive construction and destruction. You have a few options.

1. You can use the `winrt::fire_and_forget` coroutine type and ignore the result without receiving a warning.

2. You can use `co_await async` or `async.get()` to to make use of the result. 

3. You can explicitly tell the compiler that you are discarding the result without waiting/blocking using `[[maybe_unused]] auto discard = async`.

**Comment by jevansAN** [comment]
Good, that's kind of what I was looking for. So, for the benefit of the studio audience, seeking that desired folder with GetFolderAsync would read, "theFolder = co_await SomeFolder.GetFolderAsync(L"theFolderName").get();" And I could assume that theFolder would be available in the following line of code. I'll also look into fire-and-forget.

**Comment by kennykerr** [comment]
Yes, once either `co_await async` or `async.get()` returns the result, you should expect it be ready for use.

**Comment by jevansAN** [comment]
Not wanting to mislead anyone, I see that using the .get() as I described above, inside a method whose return value is IAsyncAction,
StorageFolder assetsFolder = co_await m_app_folder.GetFolderAsync(L"Assets").get();
produces an error, "This co_await expression requires a suitable 'await-ready' function and none was found." So maybe it would be better if I just call the enclosing method with an IAsyncAction result instead of ignoring the result. Also, I had better not call .get() if I don't want this to block while awaiting. I hope I'm not talking nonsense.

**Comment by kennykerr** [comment]
You're applying *both* `co_await` and `get()` to a single expression. That's never going to work. :wink:

**Comment by jevansAN** [comment]
Thanks, I'll get it right one of these days. Since I decided against get() the thing seems to go by saying, e.g. StorageFolder theFolder = co_await SomeFolder.GetFolderAsync(L"name");
