### ISSUE TITLE
auto_revoke overrides of event listeners should be [[nodiscard]]

### ISSUE THREAD

**Issue by jevansaks** [microsoft/xlang#517]
Someone on our team just ran into a bug because they wrote code like:

```
    button.Click(auto_revoke, { this, &OnClicked });
```

And then they scratched their head about why their callback didn't get called. The auto_revoke overloads of the event handlers or the event revoker should be marked as [[nodiscard]] to make this a compiler warning.

**Comment by kennykerr** [comment]
Good call. Will fix that.
