### ISSUE TITLE
wait_for silently truncates its input

### ISSUE THREAD

**Issue by tim-weis** [microsoft/xlang#525]
`wait_for` uses [`std::chrono::duration`](https://en.cppreference.com/w/cpp/chrono/duration) at the interface, but is only capable of working with 32-bit unsigned values of milliseconds in its implementation. It silently truncates durations greater than roughly 49.7 days, leading to unexpected runtime behavior.

The maximum supported duration is sufficient for almost all use cases. Still, given the versatility and simplicity of this utility, I started using it in ways, where I do not control the timeout. In my situation, the current implementation potentially causes the timeout to expire early (or not at all, if I get *really* unlucky).

Is there anything that can be done to improve this situation, e.g.:

* Document the supported input range.
* Change the implementation to work across the entire input range.
* Have the implementation report invalid input, at compile time where possible, or at runtime.
* Something else.

**Comment by kennykerr** [comment]
Thanks Tim, sounds like a good idea to document and add an assertion to help diagnose during development.
