### ISSUE TITLE
Consider alternatives to CreateFileA/CreateFileMappingA in meta_reader

### ISSUE THREAD

**Issue by micahl** [microsoft/xlang#535]
Tried to re-use the meta_reader in a "Blank App (C++/WinRT)" by including the xlang\src\Library\meta_reader.h.  Compilation fails because the CreateFileA and CreateFileMappingA API's aren't available.

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error | C3861 | 'CreateFileA': identifier not found   (compiling source file MainPage.cpp) | NativeReflection | meta_reader\view.h | 225 |  
Error | C3861 | 'CreateFileMappingA': identifier not found   (compiling source file MainPage.cpp) | NativeReflection | meta_reader\view.h | 240 |

**Comment by Scottj1s** [comment]
I very much doubt we'd go to the trouble to support the meta reader in a store app.  Was this a real scenario, or just an experiment?

**Comment by micahl** [comment]
Both, maybe?  I was _prototyping_ support in the C++ React Native for Windows project (vnext) for authoring a native extension similar to how its done in the existing C# implementation.  A developer implements an INativeModule, tags a method with the custom [ReactMethod] attribute and the method is then made available to call from the JavaScript code.  I was initially looking at rometadata.h related APIs, but they're just so cumbersome.  

Fwiw, I've worked around it for now by just renaming CreateFileMappingA to CreateFileMapping and swapped out CreateFileA with CreateFile2.  I'm now able to load the .winmd in the appx and identify which methods have the custom ReactMethodAttribute.

**Comment by Scottj1s** [comment]
oh, that's helpful - I was concerned it would be pulling a thread (more downstream issues)

**Comment by micahl** [comment]
My changes: https://github.com/micahl/xlang/commit/f84beaffa6edaa3537ac06a3a48ab335f2e3b67f.  Perhaps there's something more simple?

**Comment by Scottj1s** [comment]
I dropped a comment on your commit - feel free to open a PR
