### ISSUE TITLE
Consider removing MAX_PATH specialization in windows version of try_get_activation_func

### ISSUE THREAD

**Issue by devhawk** [microsoft/xlang#54]
@kennykerr comment from #41 PR: I'm not sure that optimizing for short paths is worthwhile. Seems like something we can add once we've profiled and determined that this is in fact a bottleneck.

@Scottj1s comment from #41 PR: or just use _malloca if you want a variable buffer that can be allocated from stack or heap as appropriate

**Comment by BenJKuhn** [comment]
This is a minor enhancement, since nothing is actually / blocked or broken, and isn't a priority.
