### ISSUE TITLE
unexpected token error after updating to today's version of C++/WinRT

### ISSUE THREAD

**Issue by sylveon** [microsoft/xlang#541]
After updating to today's build of C++/WinRT, my projects do not build anymore:
```
2>T:\Projects\TranslucentTB\packages\Microsoft.Windows.CppWinRT.2.0.190729.1\build\native\Microsoft.Windows.CppWinRT.targets(314,28): error MSB4092: An unexpected token "true" was found at character position 69 in condition "'$(_MdMergeDepth)' == '' And '$(CppWinRTRootNamespaceAutoMerge) == 'true''".
```

I think the error is related to the double ' in the condition, right after the "true" and the lack of a ' after "$(CppWinRTRootNamespaceAutoMerge)"

**Comment by Scottj1s** [comment]
fixed and new release published.  sorry folks.
