### ISSUE TITLE
clarify namespace traversal in XDN03 

### ISSUE THREAD

**Issue by devhawk** [microsoft/xlang#55]
According to XDN03, xlang_get_activation_factory first looks for an activation in a shared library that exactly matches the full type name. I.e. if searching for MyComponent.Feature.Widget, the function will first look for a library MyComponent.Feature.Widget.[dll/so/dylib]. But the implentation in #41 starts by looking for a shared library that matches just the namespace of the type (I.e. MyComponent.Feature.[dll/so/dylib]).

I'm pretty sure XDN03 is wrong here. Certainly, WinRT not considers only the type namespace when resolving metadata at runtime (a different but still relatated scenario)

**Comment by BrentRe** [comment]
The XDN03 approach has some merits. The problem with the WinRT approach is that different parties may develop / contribute different types though they all reside in the same namespace. The WinRT approach requires that the implementations of all such types be merged into in a single dll/so/dylib, typically the namespace library.

The XDN03 approach allows, if desired, each independent implementation to reside in it's own shared library. But there are two downsides:
1. When all implementations are in the single namespace library, there will be a wasted probe for the library with the class name.
2. The current design doesn't allow for classes to reside in a dll/so/dynlib that doesn't match the name of the types. It would be useful to arbitrarily map a set of types, in potentially different namespaces, to a single library.

**Comment by devhawk** [comment]
FYI, changed title of this issue because I changed the title of the XDN
