### ISSUE TITLE
Add support for win32 service hosted local servers, the ability to hook winrt::get_module_lock()

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/xlang#551]
Win32 services that host object need to inform the service controller about their ref count via CoAddRefSharedService()/CoReleaseSharedService

winrt::get_module_lock() does not have a way to redirection the operator++ and – to other functions, instead it maintains a single module specific ref count that is only visible to the C++ winrt machinery. 

If an outofproc server implemented in a service needs to idle down – and almost all should – this count isn’t very useful because the server would need to poll it, and it is not possible to prevent activation failures when a new activation races the server shutting down.

**Comment by kennykerr** [comment]
Looks like `CoAddRefSharedService`/`CoReleaseSharedService` are not public functions. It would be simpler if whatever OS functions this feature requires were actually public and thus callable from the C++/WinRT implementation. That way we can naturally support services without having to add a bunch of hooks that make the feature harder to support.

**Comment by kennykerr** [comment]
Implemented. 👍
