### ISSUE TITLE
too many arguments for function-like macro invocation 'GetCurrentTime'

### ISSUE THREAD

**Issue by vikaspachisia** [microsoft/xlang#552]
This is a pretty straightforward issue. The steps to reproduce are:

1. Open visual studio IDE with  "C++/WinRT" extension installed. 
2. Create a new CPP project "Visual C++ -> Windows Universal -> Windows Runtime Component(C++/WinRT)
3. Add a macro definition "WINAPI_PARTITION_DESKTOP" to the preprocessor macro definition list in the project settings
4. Build and resolve the normal build issue related to runtime class implementation.
5. Rebuild the project so that only 1 warning remains and this warning is the topic of the issue.

It could be two things. Either the macro definition is not allowed or it is an issue in the C++/WinRT and may or may not be fixed.

I am attaching a sample project that can reproduce the issue. The attachment also contains a screenshot of the issue. 

[UniversalRuntimeComponent.zip](https://github.com/microsoft/xlang/files/3499795/UniversalRuntimeComponent.zip)

**Comment by Scottj1s** [comment]
GetCurrentTime is a known collision between a Windows.h macro definition and a WinRT member. One solution is to #undef GetCurrentTime in your pch.h.
