### ISSUE TITLE
to_hstring could benefit from a std::wstring overload, or hstring could benefit from a std::wstring converting constructor

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/xlang#553]
Right now, going from a wstring to an hstring is somewhat onerous because of the `explicit` wstring_view constructor and the lack of an easy conversion.

This has encouraged some developers to use the following pattern:

```c++
std::wstring x; // presume existence
... to_hstring(x.c_str()) ...
```

which of course wastes a known length (retrievable from the string) by making us figure it out again.

The alternative is somewhat more verbose:

```c++
std::wstring x; // presumed
hstring y{x.data(), x.size()}; // calls ptr, len ctor
// or
hstring z{static_cast<wstring_view>(x)}; // explicit construction from wstring_view.. from wstring
```

Incidentally, `param::hstring` is _significantly better_ here as it supports wstring directly _and_ doesn't require a copy. I am sad that it is not on the allow list of namespaces.

**Comment by kennykerr** [comment]
Have you tried this:

```C++
int main()
{
    std::wstring a{ L"hello" };
    winrt::hstring b{ a };
    assert(b == a);
}
```

Will that not work?
