### ISSUE TITLE
Consider adding parallel version of C++/WinRT event source

### ISSUE THREAD

**Issue by kennykerr** [microsoft/xlang#555]
This was raised internally as a way to improve performance. Support for cancellation/timeout is also desirable.

**Comment by ChrisGuzak** [comment]
and async I assume... wil::AsyncEventSource is commonly used to mitigate poorly behaved event handlers in cases where async delivery is acceptable.

**Comment by kennykerr** [comment]
Moved to https://github.com/microsoft/cppwinrt/issues/361
