### ISSUE TITLE
What is the status of cross-platform Xlang?

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/xlang#562]
Hi,

Lately I mostly see C++/WinRT related commits, as opposed to cross-platform C++/Xlang.

Is it still being actively developed?

Do you have any estimations on when the first public version could become available (e.g. as a preview)?

Could you please provide us with an update on the status of cross-platform Xlang implementation?

Thank you!

**Comment by kennykerr** [comment]
See https://github.com/microsoft/xlang/issues/368

We continue to keep cross-platform in mind, but it is a lower priority than C++/WinRT and adding support for new languages on Windows.

**Comment by mdtauk** [comment]
So Xlang is how you bring Kotlin and Swift support to WinUI for Desktop, gotcha?

**Comment by kennykerr** [comment]
You are certainly welcome to make use of the xlang libraries to contribute something like this. 😉 

See https://github.com/microsoft/xlang/issues/513

**Comment by Alovchin91** [comment]
So, as expected, Microsoft has changed the direction again and we can stop waiting for cross-platform Xlang to happen? Oh well.

Thank you for the response.

**Comment by kennykerr** [comment]
I wouldn't call it a change in direction. From the start, I have - and our team has - steered C++/WinRT in a more open and portable direction. That is what made the idea of xlang even possible. But like any business, we have limited resources and prioritize the needs of our customers. And as members of the Windows team, our customers are predominantly Windows users.
