### ISSUE TITLE
CppWinRT failed due to error C2039: 'IUnknown': is not a member of 'xlang::Foundation' on MSVC

### ISSUE THREAD

**Issue by QuellaZhang** [microsoft/xlang#563]
Hi All,

The MSVC team build CppWinRT as a part of RWC testing to detect compiler regressions, recently CppWinRT failed due to error C2039: 'IUnknown': is not a member of 'xlang::Foundation'. Can you help look at this?

**Repro steps:**

1. open VS2109 x64 tools command
2. git clone https://github.com/microsoft/xlang F:\xlang
3. mkdir F:\xlang\build_amd64
4. cd F:\xlang\build_amd64
5. cmake -G Ninja -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX=install ..\src
6. cmake --build .\

**Build log**: [build.log](https://github.com/microsoft/xlang/files/3573426/build.log)

**Failures:**
F:\xlang\build_amd64\test\cppx\xlang/impl/Foundation.Collections.0.h(241): error C2039: 'IUnknown': is not a member of 'xlang::Foundation'
F:\xlang\build_amd64\test\cppx\xlang/impl/Foundation.Collections.0.h(5): note: see declaration of 'xlang::Foundation'
F:\xlang\build_amd64\test\cppx\xlang/impl/Foundation.Collections.0.h(267): note: see reference to class template instantiation 'xlang::impl::consume_Foundation_Collections_IMapView<D,K,V>' being compiled
F:\xlang\build_amd64\test\cppx\xlang/impl/Foundation.Collections.0.h(282): error C2039: 'IUnknown': is not a member of 'xlang::Foundation'
F:\xlang\build_amd64\test\cppx\xlang/impl/Foundation.Collections.0.h(5): note: see declaration of 'xlang::Foundation'
F:\xlang\build_amd64\test\cppx\xlang/impl/Foundation.Collections.0.h(308): note: see reference to class template instantiation 'xlang::impl::consume_Foundation_Collections_IMap<D,K,V>' being compiled

**Comment by kennykerr** [comment]
The xlang repo contains a few projects, but C++/WinRT is certainly the most actively developed. We’re in the process of splitting them out into separate repos, but for now it’s a bit of a chore to build as some of these other projects aren’t that stable or complete.

If you limit cmake to build the `cppwinrt_test` target you should be able to build just C++/WinRT and avoid the other projects. Alternatively, you can use msbuild as follows:

1. Clone the repo:

```
C:\git> git clone https://github.com/microsoft/xlang
```

2. Build the x64 Release configuration of the C++/WinRT compiler (used to generate the C++/WinRT library):

```
C:\git\xlang\src\tool\cppwinrt> msbuild /m /p:Configuration=Release,Platform=x64 cppwinrt.sln /t:cppwinrt
```

3. Build the library (a projection of the Windows API) directly:

```
C:\git\xlang\src\tool\cppwinrt> build_projection.cmd
```

This simply invokes cppwinrt.exe to generate the headers. 

At this point you can create your own console app and include the headers as needed or build the entire cppwinrt solution using x64 Debug to build all of the tests:

```
C:\git\xlang\src\tool\cppwinrt> msbuild /m /p:Configuration=Debug,Platform=x64 cppwinrt.sln
```

Hope that helps.

**Comment by QuellaZhang** [comment]
@kennykerr Thank you for providing the steps, I try them, but I got the below error from step 5(more detail see attachment), it seems that the headers conflict with windows's, how can I avoid this?

1. git clone https://github.com/microsoft/xlang d:\winrt_bak
2. pushd D:\winrt_bak\src\tool\cppwinrt
3. msbuild /m /p:Configuration=Release,Platform=x64 cppwinrt.sln /t:cppwinrt
4. build_projection.cmd
5. msbuild /m /p:Configuration=Debug,Platform=x64 cppwinrt.sln

build log:[winrt.log](https://github.com/microsoft/xlang/files/3600380/winrt.log)

error:
 C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\cppwinrt\winrt\impl\Windows.Foundation.Numerics.2.h(33): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\winrt_bak\src\tool\cppwinrt\old_tests\UnitTests\Tests.vcxproj]
         C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\cppwinrt\winrt\impl\Windows.Foundation.Numerics.2.h(33): error C2086: 'int WINRT_EXPORT': redefinition [D:\winrt_bak\src\tool\cppwinrt\old_tests\UnitTests\Tests.vcxproj]
         D:\winrt_bak\_build\Windows\x64\Debug\tool\cppwinrt\winrt\Windows.System.h(2601): error C2039: 'DispatcherQueue': is not a member of 'winrt::Windows::System' [D:\winrt_bak\src\tool\cppwinrt\old_tests\UnitTests\Tests.vcxproj]
         D:\winrt_bak\_build\Windows\x64\Debug\tool\cppwinrt\winrt\Windows.System.h(2601): error C2065: 'DispatcherQueue': undeclared identifier [D:\winrt_bak\src\tool\cppwinrt\old_tests\UnitTests\Tests.vcxproj]

**Comment by QuellaZhang** [comment]
@kennykerr Thanks for the info. I try VS2019 + Windows SDK 18362, CppWinRT is built successfully.

**Comment by kennykerr** [comment]
👍
