### ISSUE TITLE
activating a partial trust object from the dll that hosts it short-circuits the activation due to -opt 

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/xlang#565]
When creating a partial trust object in the same DLL where the implementation lives, the `-opt` behavior short circuits activation (RoActivateInstance) and the object does is not created in RuntimeBroker.exe.

This DLL has many other objects and I want to retain the use of -opt at the scope of the project.

> Scott Jones:   Or just explicitly call what that default ctor would have called:

`Foo foo(impl::call_factory<Foo>([](auto&& f) { return f.template ActivateInstance<Foo>(); }));`

But this would access the impl namespace and we should not do that... so we need support in winrt/base.h.

**Comment by kennykerr** [comment]
Thanks Chris, I'll follow up offline.

**Comment by kennykerr** [comment]
Moved to https://github.com/microsoft/cppwinrt/issues/360
