### ISSUE TITLE
C++/WinRT delegates should affect the module lock count

### ISSUE THREAD

**Issue by kennykerr** [microsoft/xlang#579]
Interface and coroutine implementations in C++/WinRT update the module lock count, but delegates do not. They should, otherwise there is no way to reliably support unloading with outstanding delegates.

**Comment by kennykerr** [comment]
This is related to #551. 

First, delegates should call `get_module_lock` during construction and destruction.

Second, there should be a way for the implementation of `get_module_lock` to be overridden for certain hosted scenarios (e.g. #551).

Third, there should be a simple way for non-libraries to get a no-op implementation of `get_module_lock` that compiles away to nothing.

**Comment by andy-schmidt** [comment]
Awesome! And I see there is already a fix. Thank you very much, I really appreciate it.
