### ISSUE TITLE
C++/WinRT hresult_error struct loses error message

### ISSUE THREAD

**Issue by andy-schmidt** [microsoft/xlang#580]
When `Windows::Data::Xml::Dom::XmlDocument::LoadXML()` encounters an XML parsing error, the `hresult_error` exception loses the message string containing the error details. `hresult_error::message()` returns `The text associated with this error code could not be found.`

Debugging, the issue appears to be because the object backing the error information only supports the `IErrorInfo` interface and not `IRestrictedErrorInfo`. One potential fix would be to have the appropriate `hresult_error` constructor call `GetErrorInfo()` to retrieve the `IErrorInfo` interface instead of calling `GetRestrictedErrorInfo()`. For error objects that support it, the `IRestrictedError` interface could then be returned from `QueryInterface()`.

This also could be a defect in the Windows Runtime. The underying implementation of `Windows::Data::Xml::Dom::XmlDocument::LoadXML()` appears to be MSXML6, and the Windows Runtime just passes through the MSXML6 error object instance rather than translating it to an error object that implements `IRestrictedErrorInfo`.

The MSXML6 HRESULT error codes do not appear to be translatable to message strings using standard techniques.

To reproduce, call `Windows::Data::Xml::Dom::XmlDocument::LoadXML()`  with a string containing a document type definition. This should throw an exception with `HRESULT` 0xC00CE584. The `IErrorInfo` description is `DTD is prohibited.` -- this is the message that should get passed through.

Develpoment environment is:
Windows 10 Enterprise 1903
Visual Studio 16.2.3
C++/WinRT 2.0.190730.2
Windows Implementation Library 1.0.190716.2

**Comment by kennykerr** [comment]
Thanks for reporting this, Andy. I'll see what I can do to propagate error information for APIs that don't use `IRestrictedErrorInfo`.
