### ISSUE TITLE
Have you ever seen MetaCall?

### ISSUE THREAD

**Issue by viferga** [microsoft/xlang#619]
Hey guys I'm doing a similar project named MetaCall (https://github.com/metacall/core). It will cover a similar field, allowing any function to be called from / to any language.

I am already supporting a variety of runtimes, as NetCore, NodeJS, Ruby, Python... and front-ends (ports), C#, Python, Ruby, C, NodeJS.. and others under construction (C++, Rust, ...).

You may be interested in it, or maybe, we can join forces. At this moment I am using this project to build an high performance FaaS. So maybe there will be some differences in each project implementation. I just had time to read some docs about design decisions and so.

What do you think about it?

**Comment by kennykerr** [comment]
Thanks for sharing! At this point, our focus is on WinRT-based tools and language projections.
