### ISSUE TITLE
[Question] Support xlang in .NET Core

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/xlang#63]
Hi everybody,

First of all thank you for this project, I think I have been waiting for something like that since the very announcement of Windows Runtime :)

I think this suggestion belongs to the actual .NET Core repo, but I just wanted to clarify some of the goals of this project.

Is support for Xlang by .NET Core on the roadmap of both projects? .NET Core badly lacks C++/CLI, and this project can easily and once and for all solve this problem, basically becoming the future of interop for .NET.

Is it being communicated between you guys and .NET Core team(s)?

Thank you!

**Comment by BrentRe** [comment]
Thanks for the positive feedback!. The xlang and .NET Core teams have been chatting about interop.

However, I'd love to learn more about your scenario. How would you use .NET Core interop with other languages using xlang? What languages are of greatest interest? What non-.NET libraries do you want to use? 

Thanks,
.   Brent

**Comment by Alovchin91** [comment]
@BrentRe Currently the only language I’m interested in interop with is C++.

At my previous company, we used to have a huge component-based architecture. The GUI of the application is written in C#, but the core of the system is C++.

The glue between the two layers was also written in C++ that was very similar to COM with some changes, first of all it should have been cross-platform (not the GUI, but C++ components). They evaluated all the other options but for some reasons they didn’t pass.

To make it work we had a huge and heavy interop generator that generated code in C++/CLI. The problem was that, a) nobody knew how that generator works, b) that of course wasn’t cross-platform. Thus ideas on how to reconstruct that appeared regularly.

With this project, that COM-like C++ API could be wrapped with Xlang components and used directly from C# code. Moreover, we had to do some magic to make it work in the opposite direction, which could also be achieved by using WinRT-like inheritance and interface implementation.

I have also faced some problems recently trying to wrap some APIs using mono/CppSharp (you can find the issues in their repo). One of the biggest challenges, currently unsolved, are the variadic functions, that are quite hard to implement in C#, especially in cross-platform way, especially in .NET Core (no ArgIterator and stuff).

Writing a C++ wrapper over the required APIs has proved its effectiveness with C++/CLI previously and I believe Xlang could help to close that gap for .NET Core really well.

I could give a more recent example if you are still interested but I not publicly :)

**Comment by BrentRe** [comment]
Thanks for the tremendously useful data. You can reach me at Brent.Rector@microsoft.com for your more recent example. :)

**Comment by Berrysoft** [comment]
I'm interested in replacing C++/CLI with xlang. I would like to use standard C++ (especially new standard) as well as interop with .NET Core. For example, coroutine will be in C++ 20, and it is very much like async/await in C#. It will be great if we can `co_await` a `Task` in standard grammar.

**Comment by Alovchin91** [comment]
+1 to @Berrysoft’s comment.

I've tried a few C# generator projects so far (namely mono/CppSharp and SharpGenTools based on CastXML) and they all fall short in terms of correctness. They are more or less configurable, but they are still not able to marshal delegates or multiple pointer indirection types, which leads to a fairly complex unsafe C# code.

I currently think of Xlang as a perfect “glue” to connect C++ and managed C# worlds, which unlike C++/CLI will be available cross-platform and unlike those generator projects (including well-known and afaik rock-solid SWIG) will not require a complex configuration in a special way or lots of boilerplate code to make it actually work.

**Comment by stevenbrix** [comment]
I'd love to see this as well it! To add on, I'd love to see xLang be a full .NET projection, no weird mix of WinRT types and .NET types. 

I filed issue #484 regarding this, since it probably warrants a different discussion entirely.
