### ISSUE TITLE
Enumerate and Connect to BLE Device?

### ISSUE THREAD

**Issue by sonus89** [microsoft/xlang#632]
Hi, I am a newbie and just started to deal with Python WinRT.
I am interested in the following modules:
```
import winrt.windows.devices.bluetooth 
import winrt.windows.devices.enumeration 
```
I would like to create a tiny script to enumerate nearby BLE devies and connect to one of them.
Is there any sample for this?

Thanks!

**Comment by kennykerr** [comment]
Unfortunately, the Python project is not currently in a usable state.

**Comment by Dibakarroy1997** [comment]
Is this possible now?

There is a C# way mentioned here: https://stackoverflow.com/q/51526156

How to do the same in Python?

**Comment by sonus89** [comment]
I used Bleak module in Python

**Comment by Dibakarroy1997** [comment]
Thanks @sonus89. I will look into it.
