### ISSUE TITLE
Documentation: Add a page which specifically details the Windows Runtime (WinRT)

### ISSUE THREAD

**Issue by duke7553** [microsoft/xlang#638]
Hi team,

I recently created an issue for the Microsoft UWP Docs repo related to better promoting various technical aspects of the Windows Runtime. 

Please see: https://github.com/MicrosoftDocs/windows-uwp/issues/2316

I'm interested in learning more about how this technology works under the hood and specifically why it's valuable. I'm aware @kennykerr offers courses for it, but wasn't sure if there are any first-party resources available to learn more about it. 

Also, @BenJKuhn thank you for responding to the thread in the WinUI repo. I know many people who will ask some great questions in this repo very soon.

**Comment by duke7553** [comment]
I also found this great information: https://docs.microsoft.com/en-us/archive/msdn-magazine/2012/windows-8-special-issue/windows-runtime-reimagining-app-development-with-the-windows-runtime#the-windows-runtime-is-fast-and-fluid-native-and-async

**Comment by kennykerr** [comment]
Hi Luke, yes you can visit https://kennykerr.ca/courses/ where there are links to various courses on COM and the Windows Runtime.

I am also starting a new project to better document the internals of the Windows Runtime. I hope to share more about that effort soon.

**Comment by DBJDBJ** [comment]
@kennykerr, I beg your pardon sir, are you no longer employed by Microsoft? Since you are selling your courses, through the "Pluralsight"... inside the issues thread of `microsoft/xlang` repo on the GitHub.  

Most peculiar that is.

**Comment by kennykerr** [comment]
Not sure what you mean. Luke mentioned the courses, so I included a link to help anyone else to find them since they're best resource I can offer at the moment (and they're not for sale).

Anyway as I said, we're working on something new that should help folks better understand the Windows Runtime.

**Comment by DBJDBJ** [comment]
In all of my innocence, I thought they are for sale. Very clear now. Thanks. 

In particular, I am interested in the architecture of it all. Architecture answers the why questions. 
Can you please point me to the relevant material?

Btw, thanks for the astonishing work on C++WINRT.
