### ISSUE TITLE
Please report in the readme.md that this project is not in a usable state

### ISSUE THREAD

**Issue by AltoRetrato** [microsoft/xlang#640]
Hi there!

Since [the xlang team is not actively working on Python/WinRT](https://github.com/microsoft/xlang/issues/622#issuecomment-562133914), and [the Python/WinRT project is not currently in a usable state](https://github.com/microsoft/xlang/issues/632#issuecomment-582003918), it would be helpful to show this right at the start of the readme.md file. It took me a couple of hours to figure the state of this project... 

Showing the state of the project might save other people time and energy, and help us know if/when we can use the project when we come back.

Thanks!

**Comment by kennykerr** [comment]
Thanks, I'll make a note of updating the readme to point out that the Python project is not usable.
