### ISSUE TITLE
Python/WinRT: how to construct an HttpFormUrlEncodedContent 

### ISSUE THREAD

**Issue by zh4ui** [microsoft/xlang#641]
Hi,

It seems Python/WinRT is not actively developed, no good document around to be found.
So I'm trying my luck here to see if someone is interested to help with my problem.

I'm playing with [Python/WinRT](https://pypi.org/project/winrt/) but couldn't find a way to  construct an instance of [HttpFormUrlEncodedContent](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpformurlencodedcontent.-ctor?view=winrt-18362#Windows_Web_Http_HttpFormUrlEncodedContent__ctor_Windows_Foundation_Collections_IIterable_Windows_Foundation_Collections_IKeyValuePair_System_String_System_String___).

The constructor of HttpFormUrlEncodedContent has the signature:
`HttpFormUrlEncodedContent(IEnumerable<KeyValuePair<String,String>>) `

I tried to pass a python dictionary as the parameter, but it failed. Apparently a dictionary is not accepted as `IEnumerable<KeyValuePair<String,String>>`.

From the document page of [HttpFormUrlEncodedContent](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpformurlencodedcontent.-ctor?view=winrt-18362#Windows_Web_Http_HttpFormUrlEncodedContent__ctor_Windows_Foundation_Collections_IIterable_Windows_Foundation_Collections_IKeyValuePair_System_String_System_String___), there is the C++ example:

```
Windows::Web::Http::HttpFormUrlEncodedContent content2{
    std::map<winrt::hstring, winrt::hstring>{
        { L"firstname", L"Jane" }, { L"lastname", L"Austen" }}
};
```

I figure that in Python, a dictionary is more or less like a std::map in C++. But I'm wrong...

**Comment by duke7553** [comment]
I did some research and it looks like IEnumerable is specific to the .NET projection. With that said, **IIterable<T>** is projected to .NET as IEnumerable<T>. This means that we need the equivalent for Python.

I'm no WinRT expert, but the documentation for Python/WinRT states:
> WinRT iterators (IIterable/ IIterator) are projected implementing the Python iterator protocol

Have you tried passing it in instead as `dict.items()` ?

**Comment by zh4ui** [comment]
@duke7553 I gave it a try, but doesn't seem to work.

```python
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from winrt.windows.web.http import HttpFormUrlEncodedContent
>>> x = {"a": "hello", "b": "world"}
>>> HttpFormUrlEncodedContent(x.items())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: The parameter is incorrect.
```

**Comment by DefaultRyan** [comment]
If you are interested in creating a fork, or another project that will consume xlang and/or the winmd reader, feel free to have a go at it. That said, we currently don't have any resources allocated for working on Python in xlang at the moment.
