### ISSUE TITLE
Question about some bug from Azure

### ISSUE THREAD

**Issue by Saibamen** [microsoft/xlang#642]
Hi,

I'm just here to connect this project and bug from https://github.com/microsoft/azure-pipelines-yaml/issues/119 (moved by me in DC: https://developercommunity.visualstudio.com/content/problem/1008354/cant-use-vsdevcmd-entrypoint-in-azure-pipelines-co.html)

**Comment by DefaultRyan** [comment]
Thanks. We're not actively using that feature right now. Feel free to close.
