### ISSUE TITLE
Porting ATL projects to Xlang for cross-platform?

### ISSUE THREAD

**Issue by forderud** [microsoft/xlang#645]
Apologies for asking a newbie question.

I'm maintaining several ATL-based C++ projects that implement COM servers with "OLE automation"-compatible IUnknown-based interfaces. These COM servers are easily accessible in-proc & out-of-proc from C++, C# (using COM interop) & Python (using [comtypes](https://pythonhosted.org/comtypes/)) on Windows. However, I also want to make them cross-platform, and am therefore interested in investigating leveraging Xlang for this if possible.

Can Xlang be used for making existing ATL projects cross-platform? If yes, then how do I get started?

**Comment by kennykerr** [comment]
There is no cross-platform support at present.
