### ISSUE TITLE
Connect to Bluetooth RFComm device example

### ISSUE THREAD

**Issue by ukBaz** [microsoft/xlang#652]
I read on issue #632 that the Python project was not in a usable state. However since then there has been a [release put on PyPI](https://pypi.org/project/winrt/#files).

If this is usable, is it possible to have an example of connecting to a RFCOMM serial port?

**Comment by Dibakarroy1997** [comment]
Any updates here?

**Comment by BenJKuhn** [comment]
Python is in a usable state generally, and it should be possible to translate the sample (sans XAML). The WinRT crew won't be able to get to this any time soon, unfortunately. We just don't have bandwidth right now to port existing samples. If you take a run at it and run into specific issues I may be able to answer questions to get you unblocked.

**Comment by kennykerr** [comment]
Please see this repo for Python support: https://github.com/pywinrt/pywinrt
