### ISSUE TITLE
Winrt DeviceWatcher Usage guide for python interaction

### ISSUE THREAD

**Issue by pbvinoth** [microsoft/xlang#657]
Hi,

We are working on python/Winrt module to interact with windows runtime Apis. We are able to see the namespace variables using the following link https://docs.microsoft.com/en-us/uwp/api/?view=winrt-19041
but while using winrt the naming convensions will be different we are able to understand the naming conventions. But while implementing in python to interact the runtime apis we are facing difficult about type error, parameter error and all.
If you have the document which helps to write the methods and registering the eventhandlers, and some spec kind of things that we need to do in our handler part.
Kindly share it.

Regards,
Vinoth P B

**Comment by kennykerr** [comment]
Please see this repo for Python support: https://github.com/pywinrt/pywinrt
