### ISSUE TITLE
LockScreen class missing in library

### ISSUE THREAD

**Issue by SidKumarSingh** [microsoft/xlang#658]
Hi

It seems the Windows.System.UserProfile projection is missing two classes - LockScreen and UserInformation. Is this intentional or accidental? And if intentional, is there any plan to include this in the future?

**Comment by DefaultRyan** [comment]
Could you be more specific? Which language projection are you referring to? It appears to be present in the C++ projection.

**Comment by SidKumarSingh** [comment]
Sorry should have been more specific. Referring to the Python projection

Thank you

Siddharth Kumar Singh
________________________________

**Comment by kennykerr** [comment]
Please see this repo for Python support: https://github.com/pywinrt/pywinrt
