### ISSUE TITLE
NotImplementedError while using Winrt in Python

### ISSUE THREAD

**Issue by pbvinoth** [microsoft/xlang#662]
Hi,

We are using the Windows.Devices.Bluetooth.GenericAttributeProfile and we are trying to start gatt service for heart rate.
We are able to find the apis which need to be used and calling the api to get the heart rate uuid and facing error like NotImplementedError. Which means in winrt this api functionality is not implemented?, I don't think so the method of calling is wrong. Could you help me get the uuids?

import winrt.windows.devices.bluetooth.genericattributeprofile as wdbgatt
gatt_uuids = wdbgatt.GattServiceUuids
heartrate_uuid = gatt_uuids.get_heart_rate()

o/p:   NotImplementedError

Regards,
Vinoth P B

**Comment by sahikon** [comment]
Root cause: Python/WinRT is missing specialization for `py::converter<winrt::guid>`
