### ISSUE TITLE
setting the BluetoothLEAdvertisementFlags in python/winrt module

### ISSUE THREAD

**Issue by pbvinoth** [microsoft/xlang#663]
Hi,

We are using the Python/winrt module, We want to publish the advertisement using the BluetoothLEAdvertisementPublisher class constructor. We are able to pushlish the advertisement but when we checked the logs it is advertising as NonConnectableUndirected, we didnt find any api to set the BluetoothLEAdvertisementType, If you know kindly share how to set the advertisement type to connectableundirected. We have option to set the BluetoothLEAdvertisementFlags as GeneralDiscoverableMode but when we used in our code we received follwing error[Parameter incorrect]. Could you help me to resolve this issue. Please let me know the way of setting this flag will be different in python winrt module.

advt_publish.advertisement.flags = 2
RuntimeError: The parameter is incorrect.

**Comment by ukBaz** [comment]
From the BLUETOOTH CORE SPECIFICATION Version 5.2 | Vol 3, Part C | 9.1.1 Broadcast mode:

> The advertising data shall be formatted using the Advertising Data (AD) type
format as defined in Core Specification Supplement, Part A, Section 1.3. A
 device in the Broadcast mode shall not set the ‘LE General Discoverable Mode’
flag or the ‘LE Limited Discoverable Mode’ flag in the Flags AD Type as defined
in Core Specification Supplement, Part A, Section 1.3.

So I would expect that to be done with [BluetoothLEAdvertisementFlags Enum](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementflags?view=winrt-19041#fields)

**Comment by pbvinoth** [comment]
> From the BLUETOOTH CORE SPECIFICATION Version 5.2 | Vol 3, Part C | 9.1.1 Broadcast mode:
> 
> > The advertising data shall be formatted using the Advertising Data (AD) type
> > format as defined in Core Specification Supplement, Part A, Section 1.3. A
> > device in the Broadcast mode shall not set the ‘LE General Discoverable Mode’
> > flag or the ‘LE Limited Discoverable Mode’ flag in the Flags AD Type as defined
> > in Core Specification Supplement, Part A, Section 1.3.
> 
> So I would expect that to be done with [BluetoothLEAdvertisementFlags Enum](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementflags?view=winrt-19041#fields)

yes since it is enum value i directory passed the flag value as 2 which is nothing but GeneralDiscoverableMode below is my actual code, If i am not using the flag i am able to publish the advertisement but the BluetoothLEAdvertisementType showing as NonConnectableUndirected which states that the device as not connectable nor scannable. Below is my code.
Please help me on changing the advertisement type as ConnectableUndirected

import winrt.windows.devices.bluetooth.advertisement as wwda

def add_status_changed(publisher, status_changed_args):
    print('status cahnged status', status_changed_args.status)

async def publish_advertise():
    advt_publish = wwda.BluetoothLEAdvertisementPublisher()
    data_writer = wwss.DataWriter()
    short_data = 0x1234
    data_writer.write_int16(short_data)
    company_id = 0x0002
    data = data_writer.detach_buffer()
    mfg_data = wwda.BluetoothLEManufacturerData(company_id, data)
    #advt_publish.advertisement.flags = wwda.BluetoothLEAdvertisementFlags.GENERAL_DISCOVERABLE_MODE
    advt_publish.advertisement.manufacturer_data.append(mfg_data)
    advt_publish.add_status_changed(add_status_changed)
    advt_publish.start()
    time.sleep(60)        # some work around time to publish the advertisements
    advt_publish.stop()

asyncio.run(publish_advertise())

If i am using the flags prameter receiving following runtime error
o/p: RuntimeError: The parameter is incorrect
--

**Comment by pbvinoth** [comment]
> Broadcast mode sha

Ok If I am not able to use GeneralDiscoverableMode and LimitedDiscoverableMode means i can set DualModeHostCapable or DualModeControllerCapable value to the flag right, at that time also facing the same issue.

**Comment by sahikon** [comment]
This problem seems to be general Python/WinRT issue with fields that has type `Nullable<T>` in WinRT.
Those fields has type `Windows::Foundation::IReference<T>` in C++/WinRT.

Looks like that Python/WinRT setters for those fields attempts to convert actual value into `winrt::Windows::Foundation::IReference<T>` using `py::converter`, but fails to do so.
