### ISSUE TITLE
new GATT service using the python/winrt Windows.Devices.Bluetooth.GenericAttributeProfile Namespace

### ISSUE THREAD

**Issue by pbvinoth** [microsoft/xlang#664]
Hi,

I am tring to create new gatt service in python/winrt module using the GattServiceProvider Class as per the
document we have to do following steps

CreateAsync(Guid) --> Which will create the new gatt service based one the guid that we are pssing.
Next the from the result of the CreateAsync(guid) we will be having the service_provider using that service provider
we need to perform startadvertising and stopadvertising. Here we have option to pass GattServiceProviderAdvertisingParameters so we can set this boolean varaibles Understood the total concept using the LE explorer application as reference
https://github.com/microsoft/BluetoothLEExplorer/blob/master/GattServicesLibrary/GattServicesLibrary/GenericGattService.cs

Below is my code

import winrt.windows.devices.bluetooth.genericattributeprofile as wdbgatt

def add_advertisement_status_changed(sender, args):

    print('status changed:', args.status)

async def gatt_advertise():

    gatt_service = wdbgatt.GattServiceProvider
    ad_param = wdbgatt.GattServiceProviderAdvertisingParameters()
    ad_param.is_discoverable = True
    ad_param.is_connectable = True
    mfg_uuid = uuid.uuid1()   # This will returns some random guid
    print('uuid:', mfg_uuid)
    result = await gatt_service.create_async(mfg_uuid)
    provider = result.service_provider
    provider.add_advertisement_status_changed(add_advertisement_status_changed)
    provider.start_advertising(ad_param)
    time.sleep(60)  # work around so publish advertisements
    provider.stop_advertising()

When I am trying to run the code receiving runtime error
o/p: RuntimeError: Not implemented

I am following the right procedure but still receiving the Not implemented error.
Could help me to start_advertising based on gatt service?

Regards,
Vinoth P B
--

**Comment by sahikon** [comment]
Root cause is the same as #662
