### ISSUE TITLE
Set BluetoothLEAdvertisementType to ConnectableUndirected in python/winrt

### ISSUE THREAD

**Issue by pbvinoth** [microsoft/xlang#665]
Hi,

We are working on Python/winrt, we have requirement to publish the advertisement using the Windows.Devices.Bluetooth.Advertisement Namespace. We are able to publisht the advertisement but in the logs the advertisment type is showing as NonConnectableUndirected which makes the device to not scannable nor connectable.

If we want to set the advertisement type to ConnectableUndirected How to set that? we are able to set the advertisement data using the Bluetooth.Advertisement name space but the advertisement prameter we are not able to set.

Help us to set the advertisement parameters particularly advertisement type

**Comment by JaiganeshKumaran** [comment]
I think this may be due to permissions for the Python executable.

**Comment by kennykerr** [comment]
Please see this repo for Python support: https://github.com/pywinrt/pywinrt
