### ISSUE TITLE
Simplify C# usage of UndockedRegFreeWinRT

### ISSUE THREAD

**Issue by AdamBraden** [microsoft/xlang#681]
asking the developer to declare DllImports is ok for a preview, but since we are building a nuget package, we should include a static class to simplify usage from C#, eg:

using System.Runtime.InteropServices;

namespace Microsoft.Windows
{
    static class UndockedRegFreeWinrt
    {
        [DllImport("winrtact.dll")]
        static extern void winrtact_Initialize();

        public static void Initialize()
        {
            winrtact_Initialize();
        }
    }
}

**Comment by ptorr-msft** [comment]
In addition / instead of the helper code, if the New Project template declares the `App` class to be `partial`, then you can just generate a `.cctor` (static constructor) in the partial code-gen file that will run before `Main`.
