### ISSUE TITLE
UndockedRegFreeWinrt - HRESULTS not throwing 

### ISSUE THREAD

**Issue by AdamBraden** [microsoft/xlang#683]
For failed HRESULT to throw, we need PreserveSig=false on the DllImport

**Comment by AdamBraden** [comment]
This is in reference to #681

**Comment by kythant** [comment]
Doesn't sound like there is anything that needs to be a fix here except for in the UndockedRegFreeWinRTManagedTest which is doing a dllImport to call winrtact_initialize() but it is not user facing. 

#681 is a good idea though we should implement that
