### ISSUE TITLE
Undocked Reg-Free should supported embedded (resource) manifests

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/xlang#684]
Currently, only loose manifests are supported.  This is an unnecessary gap from System Reg-Free, which also supports embedded manifests.

**Comment by jonwis** [comment]
The [full hunt sequence](https://docs.microsoft.com/en-us/windows/win32/sbscs/assembly-searching-sequence) is also complicated.

When looking in a dll/exe, we look for `RT_MANIFEST` and start with id 1 for the exe.
