### ISSUE TITLE
Provide a Dart projection for the Windows Runtime

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/xlang#685]
Flutter is coming to the desktop and having a projection for Dart would help those developers access new Windows APIs.

**Comment by BenJKuhn** [comment]
Tim Sneath has been doing some great work on Dart support for Windows APIs (WinRT and Win32) here:
https://github.com/timsneath/win32

I'm closing the issue here, but he's always looking for contributors.

**Comment by soumyamahunt** [comment]
@BenJKuhn would be good idea to mention those projects in ReadME.
