### ISSUE TITLE
Build and release winrt package for Python 3.9

### ISSUE THREAD

**Issue by dlech** [microsoft/xlang#709]
Python 3.9 is nearing the stable release. It would be nice to have a new release built for this in the near future.

There are also a few outstanding pull requests that would be nice to be merged before releasing.

Also, it would be nice to release for multiple Python versions so that users get the same package version no matter which version of Python they are running.

The current `setup.py` lists Python 3.7, 3.8 and 3.9 however the current release on PyPi is only for Python 3.8 and previous releases are only for Python 3.7.

**Comment by BenJKuhn** [comment]
https://github.com/actions/virtual-environments/issues/1740

**Comment by BenJKuhn** [comment]
Just posting an update. It sounds like ADO will have updated Python 3.9 support enabled early next week (based on comments in the thread linked above), so I should be able to publish the new packages shortly after that.

Thanks,

Ben

**Comment by dany74q** [comment]
Hey @BenJKuhn ! Any chance we have an ETA on having this awesome lib on 3.9 ?

Thanks !

**Comment by dany74q** [comment]
`winrt 1.0.20330.1` is now available for python 3.7 - 3.9, that's awesome, thanks @BenJKuhn !

**Comment by Kyle-Payne** [comment]
Is there an ETA on when winrt will be updated for Python 3.10?

**Comment by dlech** [comment]
The project has moved. Please use https://pypi.org/project/winsdk/ instead.

**Comment by Kyle-Payne** [comment]
Dlech, ok, so if an application like gimme-aws-creds is using winrt then it needs to be updated to use winsdk instead. Correct?

**Comment by dlech** [comment]
yes.
