### ISSUE TITLE
Couldn't retrieve Pointer info by entering PointerID

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [microsoft/xlang#711]
I am trying to get mouse location by calling ```winrt.windows.ui.input```, but specifying PointerID seems not working here:

```
import winrt.windows.ui.input as wi
wi.PointerPoint.get_current_point(1)
```

It throws

```
RuntimeError: Failed to get pointer information.
```

This shouldn't be the case, from the data I collected in a C# UWP test app:

![image](https://user-images.githubusercontent.com/32929636/95546269-b79b8f80-0a32-11eb-99f5-3724453ba7d4.png)

**Comment by jonwis** [comment]
Pointers and input are associated with windows and dispatcher loops. The identifiers are also not guaranteed to be stable across processes.  Are you calling that `get_current_point` as part of handing `WM_POINTER*` messages or other input messages in a WndProc?

**Comment by BenJKuhn** [comment]
Python support for winrt defaults to running in MTA. This causes a number of issues related to using UI features that assume STA and UI thread context. Any work to address this would be in the context of broader support for UI (which would be amazing, but isn't currently scheduled).
