### ISSUE TITLE
Add Nullability annotations to projected API

### ISSUE THREAD

**Issue by dotMorten** [microsoft/xlang#716]
.NET 3.1/NetStandard2.1 added nullability annotations to .NET Core.

Are there plans to also have the WinRT projections be annotated, so we know which members can return/accept null and which can not, so we can reduce null-checks where they aren't needed, and ensure we add them where they are?
This greatly increases the quality of the code base, as well as the quality for any apps consuming it, and reduces time spent debugging `ArgumentNullExceptions` and `NullReferenceExceptions`.

Resources:
 - [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references)
 - [Migrate existing code with nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/upgrade-to-nullable-references)
 - [Reserved attributes contribute to the compiler's null state static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis)

**Comment by dotMorten** [comment]
@AdamBraden while I realize it would be a lot of work, would it be possible to start annotating using some sort of convention though? (even if it was via an external manifest-sort-of-file that is used when generating the C# projections). The nullability feature in C#8 starts falling apart as soon as one referenced component doesn't support it

**Comment by kennykerr** [comment]
For what its worth, I also proposed this: https://github.com/microsoft/xlang/pull/708

I think it was deemed impractical to go back and annotate the many existing APIs that are known to be non-null.

**Comment by kennykerr** [comment]
> WinRT type system doesn't support nullable types.

The WinRT type system does support nullable types - most of them are nullable. The issue is that in many cases those values are known to be non-null, but compilers have no way of knowing that.

**Comment by dotMorten** [comment]
Is it possible to annotate it instead? (I realize that's a lot of manual labor but so was it with .net source)

**Comment by kennykerr** [comment]
I'm not sure what you're asking. We couldn't manually annotate the language projections even if we wanted to as they are generated (and often regenerated on demand as part of the build). The language projections are generated from winmd files (binary metadata) - the WinRT attribute I proposed could be used to annotate the definitions of the various APIs that would then feed into the winmd files so that language projections can use that information as appropriate. In the case of C#, it could use that information to apply the [NotNullAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.notnullattribute?view=net-5.0) to appropriate parameters and return types.

**Comment by dotMorten** [comment]
Yeah that's what I meant: Find a way to annotate prior to generating the wind. Or perhaps for those that have .idl files, create a way to at least annotate those?

**Comment by kennykerr** [comment]
Yep, that's what my proposal is all about.

**Comment by dotMorten** [comment]
You want us to add a ping every 10 days now?

**Comment by kennykerr** [comment]
Realistically this isn't something I see happening. https://github.com/microsoft/xlang/pull/708#issuecomment-1442186563

**Comment by kennykerr** [comment]
By the way, I'm working on new tooling for [metadata generation over here](https://github.com/microsoft/windows-rs/issues/1093). I expect that will eventually replace tools like MIDL and MDMERGE and could make it easier to express type system attributes more freely.
