### ISSUE TITLE
Python/WinRT import error

### ISSUE THREAD

**Issue by Creepercdn** [microsoft/xlang#717]
```
In [1]: import winrt
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-0eba3d78e1ae> in <module>
----> 1 import winrt

c:\program files\python38\lib\site-packages\winrt\__init__.py in <module>
      1 # WARNING: Please don't edit this file. It was generated by Python/WinRT v0.9.201125.1
      2
----> 3 from . import _winrt
      4 _winrt.init_apartment()
      5

ImportError: DLL load failed while importing _winrt: 找不到指定的模块。
```
Python Version: `Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]`
Python/WinRT Version: `winrt-1.0.20330.1-cp38-none-win_amd64.whl`

**Comment by yilmazdurmaz** [comment]
currently there are two versions seems to be available: 1.0.20330.1, 1.0.20239.1.

**v1.0.20239.1** works fine

**1.0.20330.1** has this issue

> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "T:\Tools\WinPython64\python-3.8.3.amd64\lib\site-packages\winrt\__init__.py", line 3, in <module>
>     from . import _winrt
> ImportError: DLL load failed while importing _winrt: The specified module could not be found.

@Creepercdn, if you are trying to learn like me, install running version with "pip install winrt==1.0.20239.1". It seems to be released not long ago, August 26 2020.

**Comment by ZhangTianrong** [comment]
@yilmazdurmaz I do see this version on Pypi but when I tried to install it, pip complains
```
ERROR: Could not find a version that satisfies the requirement winrt==1.0.20239.1
ERROR: No matching distribution found for winrt==1.0.20239.1
```

**Comment by yilmazdurmaz** [comment]
is possible you wrote the command wrong? `pip install winrt==1.0.20239.1`

I have just tried it on "python v3.8.6 amd64 windows" with "pip 20.2.1" and installed it. so either you wrote wrong command, you pip searches somewhere else other than pypi.org or your python/pip is broken somehow.

test command on fresh virtual environment
```
mkdir piptest
cd piptest
python -m venv .venv
.venv/Scripts/activate
pip install winrt==1.0.20239.1
```

and the result
```

> Collecting winrt==1.0.20239.1
>   Downloading winrt-1.0.20239.1-cp38-none-win_amd64.whl (4.2 MB)
>      |████████████████████████████████| 4.2 MB 3.3 MB/s
> Installing collected packages: winrt
> Successfully installed winrt-1.0.20239.1
> WARNING: You are using pip version 20.2.1; however, version 21.0.1 is available.
> You should consider upgrading via the 'w:\piptest\venv\scripts\python.exe -m pip install --upgrade pip' command.

```

**Comment by ZhangTianrong** [comment]
@yilmazdurmaz Thanks for the reply. I did use the right command. I am on 3.7.4 and pip 21.0.1, has winrt ceased to support 3.7.4? I read it requires a minimum of 3.7 in readme.

**Comment by yilmazdurmaz** [comment]
@ZhangTianrong 

I don't have 3.7.4 so I can only speculate. I checked [pypi/winrt](https://pypi.org/project/winrt/#history) page for file history. 

It seems there are only 4 version to be downloaded.

latest one, 1.0.20330.1, has the issue of this post, probably happens when ver<3.9. Again speculating because I have only 3.8 installed.

1.0.20239.1 seems to work fine, but there are files for only ver=3.8, that is why you cant install it.

1.0.19128.1 and 1.0.19119.1 have files for only ver=3.7 and you should be able to install them. But I cant say anything about their working states.

I hope the error from latest version is fixed and then supports all versions after 3.7 for the variety.

**Comment by BenJKuhn** [comment]
I did some work back in November to publish the latest version of pywinrt (with a few smaller feature updates, 1.0.20330.1) for Python versions 3.7, 3.8, and 3.9. Each package has the same version number but is built separately for the specific version of python and carries slightly different metadata to indicate which py version it supports. They should be functionally equivalent (in theory). pip should be picking the correct version of 20330.1 for the version of python you have. I don't know if there are ways to mismatch them but it sounds like maybe that's what's happening here. Can you verify the python version, winrt package versions, and also the wheel name that it installs? It should be cp##-... where ## should match the major / minor version of python that you're using.

**Comment by BenJKuhn** [comment]
ok, I was able to repro this:
...\AppData\Local\Programs\Python\Python38>python.exe
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

...\AppData\Local\Programs\Python\Python38> python -m pip install winrt
Collecting winrt
  Downloading winrt-1.0.20330.1-cp38-none-win_amd64.whl (4.2 MB)
     |████████████████████████████████| 4.2 MB 3.2 MB/s
Installing collected packages: winrt
Successfully installed winrt-1.0.20330.1
...

...\AppData\Local\Programs\Python\Python38>python
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import winrt.windows.globalization as wwg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\benkuhn\AppData\Local\Programs\Python\Python38\lib\site-packages\winrt\__init__.py", line 3, in <module>
    from . import _winrt
ImportError: DLL load failed while importing _winrt: The specified module could not be found.
>>>

I'll investigate further.

**Comment by BenJKuhn** [comment]
I was able to verify that the py38 packages uploaded with a _winrt DLL that linked against the py39 extension support. I'll have to review the pipelines to see how things got into this state and publish updated packages. There are no security-related fixes between the latest working version and the current one, so you should be safe using an older version as noted above for the time being.

>link /dump /imports ...\Python38\lib\site-packages\winrt\_winrt.pyd
Microsoft (R) COFF/PE Dumper Version 14.28.29335.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Dump of file ...\Python38\lib\site-packages\winrt\_winrt.pyd
File Type: DLL
  Section contains the following imports:
    python39.dll
             180AD42A0 Import Address Table
             180C1ED58 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference
                         349 PyTuple_New
                          27 PyBytes_AsStringAndSize
                          ...

**Comment by BenJKuhn** [comment]
Just keeping notes as I go, since I'm working on this in small spurts between other work. This is a build pipeline issue. I confirmed that the built DLLs for 3.7 & 3.8 are linking against the 3.9 APIs. That means something isn't flowing through in python version selection for the compilation step.

**Comment by BenJKuhn** [comment]
Just a heads up: Although the official build is fixed and the issue is closed, it may take me up to a day to get re-built, validated packages on pypi.

**Comment by BenJKuhn** [comment]
New version: winrt-1.0.21033.1
https://pypi.org/project/winrt/1.0.21033.1/

Let me know if you continue to see any load issues. I've updated the packages for 3.7, 3.8, and 3.9. As before, x86 and x64 packages are available. This update contains no feature changes, just fixes the DLL import that broke 3.7 and 3.8 in the last update.

**Comment by dae** [comment]
Thanks Ben, latest release seems to be working on Python 3.8 here.

**Comment by ZhangTianrong** [comment]
Thanks. It also works on 3.7.4 now.
