### ISSUE TITLE
References to same project -> MDM2009

### ISSUE THREAD

**Issue by Jacquwes** [microsoft/xlang#719]
Hello, I am facing the same problem as microsoft/cppwinrt#452, but since no solution has been provided yet, I'm creating this issue in case anyone knows some king of workaround for it. Thanks

**Comment by BenJKuhn** [comment]
This relates to a limitation in MIDLRT that is known, but has not yet been addressed. This is being tracked as an operating system bug at the moment, since that's where those tools live. I'll update this issue if / when progress is made.

**Comment by shelllet** [comment]
i have same problem!

**Comment by asklar** [comment]
Tracked internally by https://task.ms/23751686
This is affecting React Native Windows apps that use libraries who also reference WinUI: https://github.com/microsoft/react-native-windows/issues/7226
FYI @BenKuhn, this would be good to fix soon.

**Comment by shelllet** [comment]
I'm waiting hard for this problem to be fixed。
