### ISSUE TITLE
RuntimeError: No suitable kernel definition found for op Upsample(9)

### ISSUE THREAD

**Issue by xiaochenwise** [microsoft/xlang#721]
I am using WinML to report the following error:
RuntimeError: No suitable kernel definition found for op Upsample(9) (node layer86-upsample)

Is it because WinML currently does not support upsampling？

**Comment by jonwis** [comment]
Hi @xiaochenwise - this issue will get better attention over on the http://github.com/microsoft/onnxruntime repo.  (Thanks @martinb35 !)

**Comment by BenJKuhn** [comment]
Closing based on Jon's comment.
