### ISSUE TITLE
Python new winrt import & install error

### ISSUE THREAD

**Issue by andyyeyeye** [microsoft/xlang#722]
First, when I do

    pip install winrt

When I import `winrt`, I get a `ImportError: DLL load failed while importing _winrt` error
However, I found this issue already marked by `Creepercdn`, so I followed the solution and tried to install an older version; `v1.0.20239.1`

And for some reason, 

    C:\Users\andyy>pip install winrt==1.0.20239.1
    ERROR: Could not find a version that satisfies the requirement winrt==1.0.20239.1
    ERROR: No matching distribution found for winrt==1.0.20239.1

`pypi` doen't seem to have `v1.0.20239.1` available.
Why? What am I supposed to do?

**Comment by BenJKuhn** [comment]
PyWinrt is re-compiled for each supported version of python (it requires 3.7 or newer). The import error is likely the same issue as #717, which I resolved in the latest update. Let me know if you're continuing to see load issues on Python 3.7, 3.8, or 3.9 with the latest WinRT package.
