### ISSUE TITLE
Missing classes and properties which were added in newer SDKs

### ISSUE THREAD

**Issue by SamSchott** [microsoft/xlang#727]
When trying to use the Python module `winrt` to create toast notifications and handle their events, I noticed that the class `ToastActivatedEventArgs` is missing the `UserInput` property which was added in SDK version 18362.

Investigating a bit further, other classes and properties which where added in 18362 are also missing, for example `Windows.Devices.Input.PenDevice`.

Which SDK was used to build winrt? And would it be possible to update it?

**Comment by dlech** [comment]
It is currently at 17763 which is defined in the places below:

https://github.com/microsoft/xlang/blob/b950b15d53cab2dddc78c65e783ef43042a2e8c9/src/package/pywinrt/projection/AzurePipelinesTemplates/steps-build-projection.yml#L25-L27

https://github.com/microsoft/xlang/blob/b950b15d53cab2dddc78c65e783ef43042a2e8c9/src/package/pywinrt/projection/generate.ps1#L3

**Comment by SamSchott** [comment]
Thanks for the info and the PR to bump the SDK version. It is good to see some renewed work on Python/winrt!
