### ISSUE TITLE
Inserting a bytearray as parameter

### ISSUE THREAD

**Issue by sander76** [microsoft/xlang#729]
I am trying to use the `ReadBytes` method provided by the `DataReader` class to get a python bytearray. But I get stuck.

https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.datareader?view=winrt-19041

`ReadBytes` expects a `Byte[]` array. Is there a python equivalent for this ? A python bytearray or bytes object doesn't seem to do the trick.

**Comment by dlech** [comment]
On trick I found is to use a `CryptographicBuffer` API. 

```python
from winrt.windows.security.cryptography import CryptographicBuffer

...
array = bytearray(CryptographicBuffer.copy_to_byte_array(buffer))
```

The Python project currently converts .NET `Byte[]` to Python `list` and vice versa.

**Comment by dlech** [comment]
I'm hoping that we can make it so that the Python projection can treat Python objects that implement the [buffer protocol](https://docs.python.org/3/c-api/buffer.html) as an `IBuffer` so that buffers can be passed without copying.

**Comment by dlech** [comment]
See #743 for buffer protocol implementation.

**Comment by sander76** [comment]
> 
> 
> See #743 for buffer protocol implementation.

Thanks for this ! Do you need me to do something or should I just wait for a new winrt release ?

**Comment by sander76** [comment]
Low prio, unfortunately indeed.
I am happy to try out whatever you build.

**Comment by dlech** [comment]
You can find test builds at https://github.com/dlech/xlang/actions/runs/932253215 that include this change.

**Comment by sander76** [comment]
Thanks for this. Working on it now.
I've got a working version now by replacing:

```python
array = bytearray(CryptographicBuffer.copy_to_byte_array(buffer))
```

with:

```python
array = memoryview(buffer)
```

I guess this is the gist of it ?

**Comment by dlech** [comment]
It depends on what you need to do with the data in the buffer. `memoryview()` is a good choice if you want to slice the data. `struct.unpack()` is useful if the data has a fixed layout. If you want to treat the data like a stream, you can pass the ` buffer` directly to a `write()` method. There are lots of possibilities.

**Comment by kennykerr** [comment]
Please see this repo for Python support: https://github.com/pywinrt/pywinrt
