### ISSUE TITLE
pywinrt usage

### ISSUE THREAD

**Issue by HusseinElsherbini** [microsoft/xlang#734]
iam trying to detect all usb devices with class name 'measurement', according to the windows runtime api docs this line should do it : DeviceInformation.find_all_async(UsbDevice.get_device_class_selector(usb.UsbDeviceClasses.measurement))
unfortunately this isn't working, the error is an attribute type error claiming:

AttributeError: type object '_winrt_Windows_Devices_Usb.UsbDeviceClasses' has no attribute 'measurement'

sorry if this question is naive on my part but i really need help

**Comment by dlech** [comment]
In Python, run `print(dir(usb.UsbDeviceClasses))`. This will show what attributes are available. Maybe it is all caps if it is an enum/constant.

**Comment by HusseinElsherbini** [comment]
Thanks
