### ISSUE TITLE
Using DirectML from C#

### ISSUE THREAD

**Issue by vishvanathan-k** [microsoft/xlang#737]
Is there any plans to build a wrapper to use DirectML from C#

**Comment by smk2007** [comment]
Hi,

At the moment there is no direct wrapper of DirectML in C#.

However, DirectML is exposed as a backend to WinML and OnnxRuntime, and both are projected into the C# languages:

1) https://www.nuget.org/packages/Microsoft.AI.MachineLearning/
    This package supports C# UWP Apps and Desktop .NET5 applications via the WinML API.
    
2) https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime/
    This package support C# .NET Standard 2 compatible apps via OnnxRuntime Managed API.
    
You should be able to perform Inference using DirectML as a backend with either of these options in C#.

Do these solutions meet your scenario?

Thanks,

**Comment by vishvanathan-k** [comment]
Well Thanks for your quick response but I want to use DirectML to train ML.NET models . The above mentioned are all runtime for the model, they can't be used to train as far as I know.

**Comment by BenJKuhn** [comment]
Can you provide a pointer to the docs for the specific APIs that you're trying to use? I suspect there's some work that we've done that may be helpful, but we need a little more context.

**Comment by vishvanathan-k** [comment]
I was trying to run a regression model using ML.NET in C#. I have an amd gpu , so can't use CUDA. Yeah , CPU can be used but it's dataset size is around 3 Gb ,to fasten it it would be nice if we had directML support in C#. I don't know anything about DirectML nor have learnt it. Excuse me, as I can't provide you with a pointer to the API docs
