### ISSUE TITLE
Creating a background task in python does not seem to be possible

### ISSUE THREAD

**Issue by grintor** [microsoft/xlang#739]
```python
import winrt.windows.applicationmodel.background as background
taskBuilder = background.BackgroundTaskBuilder()
taskBuilder.name = 'test_task'
taskBuilder.set_trigger(background.TimeTrigger(15, True))
taskBuilder.register()
```
the register() call throws the exception `RuntimeError: Element not found.`

Are background tasks not supported by the library?

**Comment by Jaiganeshkumaran** [comment]
Background tasks need package identity. Are you using the Store version of Python? Also it does need some special registrations in the manifest which I don't think the Python application does.
