### ISSUE TITLE
pywinrt desktop notifications: how do I know when the user inputs something or presses a button?

### ISSUE THREAD

**Issue by N3RDIUM** [microsoft/xlang#741]
import winrt.windows.ui.notifications as notifications
    import winrt.windows.data.xml.dom as dom
    
    nManager = notifications.ToastNotificationManager
    notifier = nManager.create_toast_notifier(r"C:\Users\Admin\AppData\Local\Programs\Python\Python38\python.exe")
    
    tString = """
    <toast>
        <visual>
            <binding template='ToastGeneric'>
                <text>Another Message from Tim!</text>
                <text>Hi there!</text>
            </binding>
        </visual>
    
        <actions>
            <input id="textBox" type="text" placeHolderContent="Type a reply"/>
            <action
                content="Send"
                arguments="action=reply&amp;convId=01"
                activationType="background"
                hint-inputId="textBox"/>
                
            <action
                content="Button 1"
                arguments="action=viewdetails&amp;contentId=02"
                activationType="foreground"/>
        </actions>
    
    </toast>
    """
    
    xDoc = dom.XmlDocument()
    xDoc.load_xml(tString)
    
    notification = notifications.ToastNotification(xDoc)
    
    #display notification
    notifier.show(notification)

This is my code. 
How do I get a button to call a function when it is pressed?
Also, How do I get input from the text input and change the value of a progress bar?

**Comment by dlech** [comment]
You can connect events by calling `<event_token> = <object>.add_<event>(<event_handler>)`. So in your case, something like this:

```python
def handle_activated(sender, _):
    ...

activated_token = notifier.add_activated(handle_activated)

...

# later, disconnect the event handler, if needed
notifier.remove_activated(activated_token)
```

Also, be aware that `handle_activated()` will _not_ be called on the main thread.

**Comment by somePythonProgrammer** [comment]
The code gives the Error:

    Traceback (most recent call last):
      File "f:/coding/python/windowsGoodies/Notifications/test.py", line 38, in <module>
        activated_token = notifier.add_activated(handle_activated)
    AttributeError: '_winrt_Windows_UI_Notifications.ToastNotifier' object has no attribute 'add_activated'


Here is the updated code:

    import winrt.windows.ui.notifications as notifications
    import winrt.windows.data.xml.dom as dom
    
    nManager = notifications.ToastNotificationManager
    notifier = nManager.create_toast_notifier(r"C:\Users\Admin\AppData\Local\Programs\Python\Python38\python.exe")
    
    tString = """
    <toast>
        <visual>
            <binding template='ToastGeneric'>
                <text>Another Message from Tim!</text>
                <text>Hi there!</text>
            </binding>
        </visual>
    
        <actions>
            <input id="textBox" type="text" placeHolderContent="Type a reply"/>
            <action
                content="Send"
                arguments="action=reply&amp;convId=01"
                activationType="background"
                hint-inputId="textBox"/>
        </actions>
    </toast>
    """
    
    xDoc = dom.XmlDocument()
    xDoc.load_xml(tString)
    
    notification = notifications.ToastNotification(xDoc)
    
    #display notification
    notifier.show(notification)
    
    def handle_activated(sender, _):
        print([sender,_])
    
    activated_token = notifier.add_activated(handle_activated)

**Comment by dlech** [comment]
It looks like the activated event is on the `ToastNotification` object and not the `ToastNotifier` object.

**Comment by somePythonProgrammer** [comment]
It gives this;

    [<_winrt_Windows_UI_Notifications.ToastNotification object at 0x03C75560>, <_winrt._winrt_base object at 0x03C75570>]

and I need text input.
also, how do I set value of progress bars?

**Comment by somePythonProgrammer** [comment]
when I do dir(_) in handle_activated it shows

     ['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
