### ISSUE TITLE
Python: can't use CameraCaptureUI

### ISSUE THREAD

**Issue by oxygen-dioxide** [microsoft/xlang#759]
```
>>> from winrt.windows.media.capture import CameraCaptureUI
>>> cap=CameraCaptureUI()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: 不支持从 MTA 中激活单线程类
```
windows 22454

**Comment by dlech** [comment]
This is due to the fact that the library currently initializes itself as a multi-threaded apartment (MTA). Programs with a graphical user interface need to have a single-threaded apartment (STA). See discussion in #690.
