### ISSUE TITLE
Toast Notification Callback: Get name of button argument (and input text if possible too)

### ISSUE THREAD

**Issue by VellichorPrism** [microsoft/xlang#762]
Hello, #741 is not too clear as to how we can get the argument of what button was pressed on a toast notification. How can I achieve this? Below is code I have right now. I got the ```handle_activated()``` lines from #741 but it gives an error. dlech said that "It looks like the activated event is on the ToastNotification object and not the ToastNotifier object." but I am not sure how the ```ToastNotifier``` object should be used in this case. Thank you for any help.

```python
    app = my_app
    manager = notifications.ToastNotificationManager
    notifier = manager.create_toast_notifier(app)

    string = f"""
          <toast>
            <visual>
              <binding template='ToastGeneric'>
                <text>Title Message</text>
                <text>Body Text</text>
              </binding>
            </visual>
            <actions>
              <action
                content="Dismiss"
                arguments="action=dismiss"/>
              <action
                content="Open"
                arguments="action=open"/>
            </actions>
          </toast>
        """

    doc = dom.XmlDocument()
    doc.load_xml(string)
    notifier.show(notifications.ToastNotification(doc))

    def handle_activated(sender, _):
        print([sender, _])

    activated_token = notifier.add_activated(handle_activated)
```

**Comment by somePythonProgrammer** [comment]
@VellichorPrism I got a solution which doesn't answer your question fully, and can only handle one type of input. [Here](https://stackoverflow.com/questions/67588505/how-to-get-button-events-and-text-input-from-a-python-winrt-toast)
