### ISSUE TITLE
Build and release winrt package for Python 3.10

### ISSUE THREAD

**Issue by Akida31** [microsoft/xlang#763]
[Python 3.10](https://www.python.org/downloads/release/python-3100/) was released this month. It would be nice to have a release which supports python 3.10 so winrt can be used with it.
Probably this could be done like here #709 (PR for Python 3.9).

**Comment by HadyTheDiabMan** [comment]
Just to bump this issue, It really would be nice to update the winrt package for python 3.10

**Comment by Kyle-Payne** [comment]
Dlech, based on the above will there eventually be a pgwinrt version which works with Python 3.10 or should everyone migrate to winsdk?

**Comment by dlech** [comment]
Unless Microsoft transfers ownership of the `winrt` package on PyPI to me, I don't expect it to ever be updated, so using `winsdk` seems like the way to go for now.

**Comment by matanster** [comment]
Why the pessimism? :-) 
And how do `winsdk` and `winrt` relate?
