### ISSUE TITLE
[Bug] pywinrt Timeline Properties Position Value Incorrect

### ISSUE THREAD

**Issue by TurtleP** [microsoft/xlang#765]
Hi,

I've been working on a project for Discord Rich Presence stuff and I am capturing data off of Groove Music to display. I have it mostly working, but `Timeline.Position.Duration` does not report properly:

```py
from winrt.windows.media.control import \
    GlobalSystemMediaTransportControlsSessionManager as MediaManager

current_session = sessions.get_current_session()

if current_session:
    properties = current_session.get_timeline_properties()
    position = timedelta(microseconds=properties.position.duration / 10)
    print(position)
```
This always prints `0:00:00` (at least in Groove Music as far as I've tested). I haven't tried anything like Spotify or using Youtube, but I *did* try the new Windows 11 Music Player app (on my laptop which runs the insider builds), which seems to report a proper value.

Operating System: Windows 11 (21H2)
Python Version: 3.10
pywinrt Version: [artifact from here](https://github.com/dlech/xlang/actions/runs/1305498290)

---

The goal I want is to find out the total duration of the media and the current progress of its playback, if possible. Though I do want to support more than just using Groove Music and I don't know if any other media players support using this data. Regardless, it might be a bug that isn't pywinrt-related, more towards Windows things, but I thought it should be reported just in case.

**Comment by SurajBhari** [comment]
@TurtleP you found any solution for this ?
