### ISSUE TITLE
pywinrt: precompiled header does not improve build time

### ISSUE THREAD

**Issue by dlech** [microsoft/xlang#768]
The current precompiled header for pywinrt doesn't include many files and therefore doesn't really improve the compile time. I've been experimenting in my fork and was able to decrease the compile time to about 1/3 of the current time.

First, I followed [this blog post](https://devblogs.microsoft.com/cppblog/faster-builds-with-pch-suggestions-from-c-build-insights/) to do a performance capture. This showed that many of the generated header files were being parsed hundreds of times. So I changed things around to precompile all of the header files to get the performance improvement.

Here are the actual logs that can be viewed with [Windows ADK](https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install).
[pywinrt_before.zip](https://github.com/microsoft/xlang/files/7797010/pywinrt_before.zip)
[pywinrt_after.zip](https://github.com/microsoft/xlang/files/7797009/pywinrt_after.zip)

Here are the related commits: https://github.com/dlech/xlang/commit/9799d543a8368e9fb1796dd58578eb9f5845e73, https://github.com/dlech/xlang/commit/05c56564c385f01d2e5478cedaa97d2f45f95a01, https://github.com/dlech/xlang/commit/5bf5c9e4e141cf8c974b6a5aaad56f0333912d57.

**Comment by BenJKuhn** [comment]
closing since pywinrt is now maintained in a new repo / project.
