### ISSUE TITLE
Python/WinRT wheel file on PiPy for Python 3.10

### ISSUE THREAD

**Issue by Crypto-Python** [microsoft/xlang#777]
Python 3.10 has been released in October 2021 and we would like to support it in our application https://github.com/Cryptnox-Software/cryptnoxpro. We're using winrt for interfacing with Windows Hello to unlock our cards with it.
On the PiPy page if winrt there are wheel files for 3.7, 3.8, and 3.9: https://pypi.org/project/winrt/#files
Is there a plan or release date for the wheel file for Python version 3.10? 

```
Python310\python.exe -m pip install winrt
ERROR: Could not find a version that satisfies the requirement winrt (from versions: none)
ERROR: No matching distribution found for winrt
```

**Comment by dlech** [comment]
You can use https://pypi.org/project/winsdk instead. It supports Python 3.10 and has many bug fixes compared to the `winrt` package.

**Comment by Crypto-Python** [comment]
It works flawlessly. Maybe winrt could add into their readme that it's not supported and point to winsdk as a replacement.
