### ISSUE TITLE
UndockedRegFreeWinRT does no error checking on Detours calls

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/xlang#782]
Nearly all the Detours functions return an error code.  But [InstallHooks](https://github.com/microsoft/xlang/blob/cfe510d0d2b07484fea2c6d77163de017738c100/src/UndockedRegFreeWinRT/UndockedRegFreeWinRT/dllmain.cpp#L324) does not check for errors.  It should do so and return FALSE from DllMain if necessary, and both native and managed client apps should fail on such errors.

**Comment by DrusTheAxe** [comment]
Windows App SDK's fork does this. That currently has an issue it's disabled for packaged apps (i.e. if process has package identity). I'm working on a fix.

Is xlang/URFW under active development and a peer to WinAppSDK/URFW? Or is xlang, er, sleepy, and new development focused on WinAppSDK?
