### ISSUE TITLE
【winrt】Failed to import JapanesePhoneticAnalyzer

### ISSUE THREAD

**Issue by nai-kon** [microsoft/xlang#783]
Failed to import JapanesePhoneticAnalyzer of Windows.Globalization.
```
>>> from winrt.windows.globalization import JapanesePhoneticAnalyzer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'JapanesePhoneticAnalyzer' from 'winrt.windows.globalization'
```

I found there are no python binding for JapanesePhoneticAnalyzer on below source.
`\site-packages\winrt\windows\globalization\__init__.py`
"JapanesePhoneticAnalyzer" is not support yet?

[API Reference] Windows.Globalization.JapanesePhoneticAnalyzer
https://learn.microsoft.com/en-us/uwp/api/windows.globalization.japanesephoneticanalyzer?view=winrt-22621

**Comment by dlech** [comment]
This API is part of the Desktop extensions and is not included in the `winrt` package. You can use the [winsdk ](https://pypi.org/project/winsdk/) package instead, which has Desktop extensions included (and many other bug fixes and improvements).

**Comment by nai-kon** [comment]
Thank you for your help.
Close this issue.
