### ISSUE TITLE
Undocked regfreewinrt binaries are not included in application when using custom VS build configurations

### ISSUE THREAD

**Issue by BenJKuhn** [microsoft/xlang#786]
If msbuild variable $(Configuration) is neither "Release" nor "Debug" the targets in Undocked RegFree WinRT don't kick in and work their magic, resulting in an application that won't run. It probably makes sense to default to release configuration if the configuration variable is unrecognized.

**Comment by DrusTheAxe** [comment]
Makes more sense to error on invalid values. And easy enough to do
