### ISSUE TITLE
Adopting GSL

### ISSUE THREAD

**Issue by phoyd** [microsoft/xlang#83]
XLDN02 lists the  [C++ Core Guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md) (CCG) as a coding guideline for C++ code. CCG recommends the use of [GSL](https://github.com/Microsoft/GSL) to express the ideas formulated in the guidelines. 

Proposal: 

* GSL should be made available to the private xlang interface, probably as a submodule. 
* The [CCG Checks](https://clang.llvm.org/extra/clang-tidy/checks/list.html) of clang-tidy should be added to the build.

**Comment by phoyd** [comment]
gsl::span would be nice to replace the (<some_pointer>,<data_length>) pairs in the string library until std::span from C++20 is here. Also, I like the idea of having some kind of gsl::not_null. 

I'll open an extra issue for clang-tidy.

**Comment by kennykerr** [comment]
As Harry mentioned, we try to limit our dependencies on those facilities that are in the standard library. 

Also, keep in mind that the PAL is meant to provide a minimal C/COM ABI that language projections rely on, but that developers never interact with directly. Language projections like C++/WinRT work very hard to shield developers from having to manipulate pointers and instead provides value semantics and span/view-like abstractions as appropriate.

**Comment by phoyd** [comment]
I see. The minimal dependency guideline seems like a good idea to me, I will try to keep this in my mind.
