### ISSUE TITLE
Use clang-tidy for code conformance checks

### ISSUE THREAD

**Issue by phoyd** [microsoft/xlang#84]
CMAKE 3.6 and up supports building targets with a _clang-tidy_ step on the target compilation database out of the box. clang-tidy has a growing number of code compliance checks, which should be useful to keep the code clean. It should be easy to integrate into the build system.

**Comment by DefaultRyan** [comment]
I spun up a branch where I got clang-tidy running as part of the build. https://github.com/Microsoft/xlang/tree/defaultryan/clang_tidy

There’s a lot of spew right now. Some checks are more useful than others. But once we agree on a baseline, it may make a nice target to build pull requests against. Right now it's enabled in all clang builds, but depending on how severely it impacts build speed, it may make sense to configure it to run only on certain targets.

Just something to iterate on in spare time, and converge it towards merging into master.
