### ISSUE TITLE
use std::filesystem instead of std::experimental::filesystem

### ISSUE THREAD

**Issue by devhawk** [microsoft/xlang#85]

**Comment by ChrisGuzak** [comment]
yes, `std::filesystem` is now offical, use it instead of `std::experimental::filesystem`.
I saw this in the idl.exe sample.

**Comment by devhawk** [comment]
libc++ release 60 - which is to say the version we are currently using to compile xlang for ubuntu - only supports `std::experimental::filesystem`.  Release 70 supports `std::filesystem` so we can do this after we upgrade our ubuntu tools. But I want to get xlang running on mac (tracked by #35) before we update our ubuntu tooling.

**Comment by ChrisGuzak** [comment]
Makes sense.

**Comment by kennykerr** [comment]
Ryan, can you figure out how to get this done at some point as the Linux build is now broken.
